### ISSUE TITLE
Feature Request: Add 'hasStock' orderBy param to product

### ISSUE THREAD

**Issue by hannahwoodward** [craftcms/commerce#1006]
### Description
A client has requested that they would still like out of stock products to be shown on a products listings page, but only after all the products with stock. Since the listings page has pagination, I've been struggling to combine this into a single query to pass into the {% paginate %}` tags

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.4
- Database driver & version: mysql 5.7.25
- Plugins & versions: Commerce 2.1.13

**Comment by lukeholder** [comment]
This isn't possible at the moment due to the current `hasSales` implementation under the hood.

In the mean-time you would need to run 2 queries, one to get the IDs of the the product/variants on sale, then do another query for all products (the one that would be paginated), and order that query by the IDs of the first query. Something like the below should work on MySQL using the field function as an expression in the orderBy param:

```
{% set productIds = craft.products.ids()|join(',')%} // query with sales
{% set byIdsExpression = "FIELD([[elements.id]],'~productIds~')" %}
{% set products = craft.products.orderBy(expression(byIdsExpression)).all() %}
```

**Comment by daniellelecomte** [comment]
Hi @lukeholder - is this still the best way to get out of stock product to show at the end of a products array? Thanks!
