### ISSUE TITLE
Add RMA functionality

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#1046]
Would fix #803 and #952

**Comment by engram-design** [comment]
To save people some Googling - return merchandise authorisation (RMA). 

In my scenario, one of our clients is pretty strict with their stock levels, and having cancelled orders should return stock to their products. I imagine this RMA system would handle that? My issue is similar to https://github.com/craftcms/commerce/issues/952

What's tricky - and I imagine this is what a larger system is for - is how to define when product stock needs to return. You might have two scenarios: 

1. Customer receives their product, but wants a refund (partial or otherwise). Stock shouldn't be added back, despite the refund.

2. Customer cancels their order after paid, but before shipped. Shop admin's change the order status to "Cancelled" and stock returns to the product. Their payment is refunded.

**Comment by yoannisj** [comment]
For consideration: I ran into a project which could use line-item refunds to create an internal document which details refunded items for accounting (much like an invoice with negative values).

I guess if there was a way to extract the line items that were refunded based on the order's transactions or history, this could be done without guess-work.

**Comment by samhibberd** [comment]
@lukeholder about to embark on building out some custom line item refund logic, we really need it for a project we are about to launch. As it's fairly involved, I thought best check up on the status of this or similar stuff in development and whether it would impact our decision to write our own. Happy either way just be good to know the state of things?

**Comment by lenvanessen** [comment]
@samhibberd did you ever get around to building the logic yourself? Would love to see our approach, currently running into the same issue.
