### ISSUE TITLE
Allow Order ID to be searchable in the order element index

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1077]
It seems like you can't search by the Order's ID in the element index?

Notably, we can search via the Reference, Short Number and Full Number.

**Comment by lukeholder** [comment]
Not possible for any element at the moment, and not sure if even possible. Looking into it.

**Comment by engram-design** [comment]
@lukeholder Didn't even realise this doesn't work for other elements, but thanks for looking!

**Comment by RitterKnightCreative** [comment]
@engram-design I assume you're asking about ID (and not Order?) since there's no Order ID field?

The ID skips around way too much (not sequential) to be practical for front-facing customer orders so setting a customer order/reference number is the only sane way to use/query for orders....TBH  how did you end up using it?

![Screen Shot 2019-10-29 at 1 52 03 PM](https://user-images.githubusercontent.com/3707869/67799420-519d3e80-fa53-11e9-91db-3f020660d70a.png)

**Comment by engram-design** [comment]
@RitterKnightCreative I'm talking about the order element ID, but yes, as a column, its labelled as just "Order". And its used in a variety of ways

For instance, the payment is sent to Stripe and other gateways only contains the Order ID, not the reference. If you wanted to look up the corresponding order in Craft, its not really possible, because you can't search by order ID.

It was also more just for convenience, as a bunch of our logging shows the Order ID - but we've since changed this to the reference number.

**Comment by j-greig** [comment]
We have a client requesting this too.

**Comment by rjhewitt3** [comment]
We also have a client requesting this! @lukeholder I'm assuming your investigation didn't yield "impossible" as the result?

**Comment by lukeholder** [comment]
Order IDs are the Element IDs and are not searchable by Craft CMS, if you want the ID to be searchable put it into your order reference format like this: `{id}`. This reference is searchable on the order index.

Submit a ticket to the `craftcms/cms` repo if you want this feature.
