### ISSUE TITLE
More Fields / Sortable on Order Index Page

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#1089]
### Description
On the orders index screens, surprisingly, the Phone number is not something that's not searchable or even showable.  

You can search by name and email address, I assume because those are "required" fields in order process? If a customer calls in, it shouldn't be hard to cross reference their orders automatically with the phone number. 

So it would be great to add more fields to the sources... for example, state, so we could theoretically show all customers who ordered in that state, etc.

Also, some fields are not sortable. Why is Reference sortable but not Order? That makes it slightly confusing especially if we have a custom order number sequence.  We usually end up sorting by date ordered for example but it's still a redundancy.

![Screen Shot 2019-10-29 at 1 18 16 PM](https://user-images.githubusercontent.com/3707869/67796831-b4400b80-fa4e-11e9-98ca-a049347dd2d7.png)

### Additional info

- Craft version: 3.3.7 / 2.1
- PHP version: 7
- Database driver & version:
- Plugins & versions:

**Comment by lukeholder** [comment]
If you want to extend the sources list in the side nav you can add sources with the `\craft\base\Element::EVENT_REGISTER_SOURCES` event. This would let you make a filter that shows orders by state etc.

I have added shipping and billing address phone numbers to the order search index for the next release of Craft Commerce 3.

The order column is not sortable because the data is not consistent between orders and carts (reference is blank for carts), and at the moment, the cart element index pages don't allow customising the first column based on the source you are looking at.

If you have exact columns you want added to the order search index make a new ticket with the list of columns.

e11adfc03d385a0af3e2a76d37c4238a3f743712
