### ISSUE TITLE
Order::getAdjustmentsTotalByType() has been deprecated.

### ISSUE THREAD

**Issue by circa1977** [craftcms/commerce#1310]
### Description

I'm seeing the following in my deprecation warnings:

>  Order::getAdjustmentsTotalByType() has been deprecated. Use Order::getTotalTax(), Order::getTotalDiscount(), Order::getTotalShippingCost() instead.

This makes sense and easy enough to fix. But in my `cart.twig` I also have the following:

`cart.adjustmentsTotalByType('fee')`

That's an adjuster I wrote that adds a line item admin fee to every order.

How do I get my custom adjustments if that goes away? Can an argument be made that it's clearer to use a single function name in the template with each corresponding fee as an instance?

### Additional info

- Craft version: 3.4.2; Commerce 3.0.5

**Comment by nfourtythree** [comment]
Hi @circa1977 

The reason for this is because we will be dropping support for custom adjuster types.

There are a number of reasons for this one of which is that it is difficult to reconcile an order for gateways when there are a number of adjustments that the system doesn't "understand".

We are transitioning to dynamic line items in future versions.

Thanks.

**Comment by circa1977** [comment]
@nfourtythree So there's no way to keep deprecation errors from piling up for my custom adjuster that adds an admin fee to every order? :)

**Comment by nfourtythree** [comment]
Hi @circa1977 

Unfortunately, we need to keep the deprecation notice in there to warn people that the method and subsequently custom adjust types will be removed in a future version.

Thanks.
