### ISSUE TITLE
FR: Variant Name in Manual Order Screen

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1352]
### Description
Currently, when adding a line item to a manual order, you only see the sku & variant name, and not the parent product name. 

We keep our variant names simple, i.e. "Blue", "10 Pack", so the lookup is not very helpful.

Is there a way to show the product name alongside the variant name as well?

Thank You

Craft Commerce 3.1

**Comment by nfourtythree** [comment]
Hi @keyurshah 

The "descriptions" column in the add a line item table comes from the "Order Description Format" setting for the product type:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/p9uK1zoz/Screenshot%202020-04-03%20at%2010.46.49.png?v=e8f21623ef9267a959bbc369b4aa0cb1)

This is because this table is for all purchasables, both built-in (e.g. variants) and any custom ones that might be registered by other plugins or modules.

It is the same attribute that is used for consistency through line items and orders.

So the best way would be to get this updated to be correct and this should solve your issue.

Thanks!

**Comment by keyurshah** [comment]
Thank you. I changed that but it still looks the same in the manual order screen. Do i need to run anything after making the change?

**Comment by nfourtythree** [comment]
Hi @keyurshah 

This should have trigger a re-save of products, will check on that.

In the meantime, you can run the CLI command `./craft resave/products` this should update this data for you.

Thanks

**Comment by keyurshah** [comment]
thanks, it works after running that command.
