### ISSUE TITLE
Add ability to avoid search index updates

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/commerce#1416]
### Description
In larger sites e.g. 1000's of products and carts the queue is constantly filled up with search index updates as Commerce uses Crafts saveElement function which updates the search index each time.

It would be great if some how this could be disabled.

I wasn't sure if this is the right place to post as I know the culprit here is the Craft saveElement function.

**Comment by lukeholder** [comment]
Do you have your queue running automatically, or only when someone hits the CP?

Since emails are on the queue now most people set https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically to false and have their own always-running daemon, or a cron job to run the queue. This should reduce the number of jobs you see in the queue (if that's what the customer is having an issue with?).

**Comment by mediabeastnz** [comment]
The "issue" is Commerce (because of Craft) saves the order/cart everytime a small update is made. E.g. qty updates, new lineitem, new cart etc etc. This is obviously required but I don't really see why the searchIndex needs to be updated for carts.

It's almost like the Orders/Carts need their own save function rather than piggy backing of `SaveElement()`

**Comment by lukeholder** [comment]
Fixed for the next release, you can now use the config option:

## `updateCartSearchIndexes`

Determines whether the search index should be updated when a cart is saved by a customer when they use the `commerce/cart/*` controller actions.
Making this `false` will reduce the number of search index update jobs created, but will also reduce the ability to search carts in the control panel. 

Default `true`

**Comment by mediabeastnz** [comment]
Thanks @lukeholder 🙌
