### ISSUE TITLE
Individual Product 'Free Shipping' option not being recognised

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#1440]
### Description

The option to enabled 'Free Shipping' specifically within a product entry doesn't appear to be working. I have enabled this on a product, but then no deductions to the shipping is when in the checkout process. Surely if this product is in the basket, it should simply be the case that there is no shipping cost?

I have not got any additional sales / discounts applied which could possibly be interfering with it. 

Are there any known issues with this feature? 

<img width="368" alt="Screenshot 2020-05-06 at 13 29 46" src="https://user-images.githubusercontent.com/6592882/81176864-b22aac80-8f9d-11ea-9c3c-7fd5f43eec15.png">

### Additional info

- Craft version: 3.4.9
- PHP version: 7.0.33
- Database driver & version: 5.7.30
- Plugins & versions: Commerce 2.2.17

**Comment by lukeholder** [comment]
Not able to reproduce this. The shipping cost is not being applied to line items with a per item shipping cost.

If you are talking about a shipping rule that adds a base shipping cost, then the 'free shipping' flag on that product does not remove the shipping cost of the whole order if that shipping method is selected, and it is expected behaviour. Base shipping cost is an order shipping cost, not a product cost. Do you have a base shipping cost set up, maybe that is the cost you are seeing?

**Comment by iamtompickering** [comment]
Ahh okay, if that's the case then yes it will be the base shipping cost that I am seeing. 

Might sound a bit dumb here but please would you be able to explain how I would go about setting up shipping costs on a per item basis in order to allow us to use this free shipping option?

**Comment by lukeholder** [comment]
![image](https://user-images.githubusercontent.com/133571/82288966-43564600-99d6-11ea-8391-f8110db2a63a.png)

The above arrow is to the per item rate per item. If you set up categories, you can also have per category pricing overrides below (only general category is shown at the moment)
