### ISSUE TITLE
Per Email Address Discount Limited coupons before checkout

### ISSUE THREAD

**Issue by tom-c** [craftcms/commerce#1455]
**Description**
Not sure if this a bug or expected behaviour but I'm trying to give email newsletter signups a 'Per Email Address Discount Limited' single use coupon to use on their first purchase. This means they are always a guest to start with before checkout. 
If you try to use a single use coupon without an email address (e.g. in cart) the coupon shows as 'This coupon is limited to 1 uses'. The discount only works if they proceed to checkout and use an email address that's not already had the discount and then apply the coupon. It seems the system returns 'discountPerEmailLimitValid' false if there's no email address in the cart (line 960 in commerce\services\Discounts.php).

**Expected behaviour**
I expected the discount to always work for guests so their cart reflects the correct price before proceeding to checkout where they apply their email address and details. I know I expect that as a user on other sites and often check that a coupon is valid and gives me discount before proceeding with filling out forms and handing over my data.

**Additional info**
- Craft version: Craft Pro 3.4.20
- PHP version: 7.4.1
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.4

**Additional context**
Really I'm using this as a work around as I'd like to use unique coupon per new customer but there's no easy way to bulk create coupons (and use them in Mailchimp) at this point without a lot of custom API faffing.

**Comment by nfourtythree** [comment]
Hi @tom-c 

We have a number of plans for improving discounts and coupons in the future, however, these are likely to be breaking changes and therefore will only be in a major update.

For a solution (although I understand the following is not ideal) you could submit a temporary email address with the coupon code in a hidden field e.g. `myrandomstring123@guest-checkout.com`

This would then mean that the discount would be valid. Then anywhere you output the email address (e.g forms, cart summary, checkout summary etc) you can check the email and if it equals your temporary email you can not show it. The customer would obviously overwrite this with their own email further in the checkout process.

Thanks.

**Comment by tom-c** [comment]
Thank you for replying and explaining – having watched the other issues and codebase I figured as much. 

I've experimented with using temp emails and real emails (using query string based links when emailing customers coupons) but it presents a new set of problems in blocking checkout advancement if they've already used the coupon or if they edit their email address to one that's already used the coupon. It's workable but feel like odd user experience if they're not paying attention to validation messages about the coupon.

I guess my other option is to build a customer adjuster to apply 'cart' discount and then remove and apply real discount once within the checkout flow.

For now I've had to apply the coupon redemption later in the checkout flow after they've completed their email which isn't perfect but client doesn't have the time or budget for a more complex solution right now.

Fingers crossed for the future changes improving this.

Tom

**Comment by nfourtythree** [comment]
Hi @tom-c 

With the recent addition of order notices and an update we have just pushed this issue will be fixed in the 3.4 release of Commerce (#2181).

There will now be a specific error message related to the fact that an email will is required for the `perEmailLimit` conditioned coupon to work.

Thanks.

**Comment by tom-c** [comment]
Ace, thank you for letting me know 🙏

**Comment by terryupton** [comment]
I am still having issues with this following an upgrade.
If the user is a guest and at the cart (where no email address) has been entered then this still returns nothing.
No error or applies the discount. So it just appears to be broken to the end-user.

What I would expect to happen is if no email address exists, for the code to be applied and then later re-check once the email address has been entered if it is valid or not.

Can you confirm if this was fixed in the release? It was referenced as fixed in 
**3.4.0 - 2021-07-13**
https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#fixed-5
_Fixed a bug where discounts weren’t displaying validation errors for the “Per Email Address Discount Limit” field. (#1455)_

**Comment by watarutmnh** [comment]
I have the same. No error returned when no email address set on cart.

**Comment by pixelmachine** [comment]
Can confirm that there is no error message in Commerce 3.4.18 @nfourtythree @brandonkelly 

This is especially inconsistent behaviour because as per #2925 coupons will be applied in other situations even when nothing matches and they have no effect!
