### ISSUE TITLE
[3.1.4] Customer deleted when `registerUserOnOrderComplete` is true

### ISSUE THREAD

**Issue by martinleveille** [craftcms/commerce#1456]
**Description**
Customer got deleted when `registerUserOnOrderComplete` is true when checking out as a guest.

This bug was introduced in 3.1.4.

**To Reproduce**
How, and what happened?
1. Install Craft and Commerce.
2. Copy the provided example `shop` templates.
3. Open an incognito browser window to make sure no user is logged in.
4. Navigate to the `/shop` url and add a product in the cart.
5. Make sure to checkout as a Guest, not as a registered user.
6. At the payment step, check the `registerUserOnOrderComplete` checkbox.
7. Error returned: `No customer exists with the ID “2”`.

**Additional info**
- Craft version: 3.4.20 Pro
- PHP version: 7.3.18
- Database driver & version: MySQL 5.7.29
- Plugins & versions: Craft Commerce 3.1.4 Pro

**Comment by engram-design** [comment]
Also seeing this behaviour. I believe its due to this line - https://github.com/craftcms/commerce/blob/develop/src/services/Customers.php#L806 and removing this makes things work as expected.

I'm not familiar with these latest set of changes and why there's the need to have two customers. In the past, when I've rolled my own solution for this, I've simply assigned the userId to the customer and saved the customer. Maybe I'm missing something in the updated behaviour.

Can you advise?

**Comment by engram-design** [comment]
For now, I've modifying:
```
if ($autoGeneratedCustomer) {
    $this->deleteCustomer($autoGeneratedCustomer);
}
```

to check to see if there's an actual difference in the customers:
```
if ($autoGeneratedCustomer && $customer->id != $autoGeneratedCustomer->id) {
    $this->deleteCustomer($autoGeneratedCustomer);
}
```

**Comment by lukeholder** [comment]
Taking a look at this now.

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#18c1671781bd767e18f852b3f618bb088b33abbf as 3.1.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lukeholder** [comment]
Yeah, we wanted to make sure the user that gets saved on registration, if it makes a new customer, we don't get 2 customers with the same related user. Fixed for the next release.
