### ISSUE TITLE
Duplicated Queries

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1469]
**Description**
When adding to cart, the number of queries seems very high, with many duplicates.

**To Reproduce**
1. Turn on debugbar
2. Add item to cart and observe the POST request

**Expected behavior**

I expected to see the number of queries to be much less. In the craft commerce default shop templates, I see what seems to be many duplicate queries.  I am guessing that they are separated for performance reasons, but it still seems very high. And I see queries for commerce transactions even when I am just adding the item to the cart. 

![image](https://user-images.githubusercontent.com/744385/82963880-d2d09b80-9f78-11ea-98ff-464d4230a3a4.png)

![image](https://user-images.githubusercontent.com/744385/82964139-86d22680-9f79-11ea-934d-063acdbdf4c5.png)

![image](https://user-images.githubusercontent.com/744385/82964178-a6694f00-9f79-11ea-8449-56fe65548e3f.png)

On my production site, when adding to cart , i get 492 queries with 420 duplicated (in the POST request)

![image](https://user-images.githubusercontent.com/744385/82964307-04963200-9f7a-11ea-9aaa-f38021cd9bd1.png)

**Additional info**
- Craft version: Commerce 3.1.4

**Comment by nfourtythree** [comment]
This was fixed along with some other pieces in #1603

Thanks!

**Comment by samhibberd** [comment]
@Anubarak we are running into similar issues with hugh numbers of duplicate queries, was the only solution your custom  wrappers to handle eager-loading or did you find any other ways to work around?

**Comment by Anubarak** [comment]
@samhibberd Fortunately later versions of Commerce fixed many of these issues (and introduced new one) but ultimately in case you cannot update your system all you can do is to not use commerce functions directly.

Unfortunately there is no other good way as Craft / Commerce does not use Yii2 Containers to their fullest advantage so you cannot extend their classes and fix issues. I had to spend many days on this as well.

**Comment by Anubarak** [comment]
I wish you good luck.
For smaller changes that are fixed in later releases I sometimes changed the source-code directly. This is of course not best practice but sometimes it makes more sense time-wise.
For example if you only have one single currency you can go the lineItem contructor/behavior (depending on your version) and set the currency directly.

Commerce 3 handling was:
- fetch an order and call `getLineItems()`
- order will fetch the lineItems
- lineItem constructor/behavior will then fetch the order from the DB in order to get the currency
-> load an order with 10 LineItems and you'll query the order 11 times

https://github.com/craftcms/commerce/blob/3.3.4/src/models/LineItem.php#L234

So it's easier to remove the `$this->getOrder()->currency` part instead of trying to build around it.
