### ISSUE TITLE
SendEmail job is fired when PSP marks order as complete, but PSP doesn't run queue

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1474]
**Description**
SendEmail job is fired when PSP marks order as complete, but PSP doesn't run injected queue javascript when runQueueAutomatically is set to true.

So the order email is only sent when someone is logging in to the CP

**To Reproduce**
How, and what happened?
1. Create an order and have a PSP with a webhook complete the payment
2. Wait for status email to come in
3. When it doesn't, log in to CP
4. See status email come in...

**Expected behavior**
Queue is run by webhook or after redirect to thanks page

**Additional info**
- Craft version: latest
- PHP version: latest
- Database driver & version: Postgres
- Plugins & versions: Commerce latest

**Comment by boboldehampsink** [comment]
Workaround: Put `{% do craft.app.queue.handleResponse %}` in your thanks page.

**Comment by lukeholder** [comment]
Since webhooks run outside of the clients request, we can't add the ajax queue runner script to the page automatically - the way you have done it is a good workaround to the new recommendation of using a queue worker set up as a daemon or cronjob.

https://docs.craftcms.com/commerce/v3/upgrading.html#order-emails
https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically
