### ISSUE TITLE
Total Paid in order index is always $0

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1482]
Total Paid in order index is always $0, despite it being correct when viewing the order detail screen.

Refer to:
![Screen Shot 2020-06-01 at 2 41 51 pm](https://user-images.githubusercontent.com/1221575/83376658-59bcc280-a416-11ea-81c8-adcfa4b3ce82.png)

But is all correct:
![Screen Shot 2020-06-01 at 2 44 15 pm](https://user-images.githubusercontent.com/1221575/83376669-680ade80-a416-11ea-8016-bc77a684bbf2.png)

In addition, there are multiple "Total" options to pick from in the element index, which is confusing.

![Screen Shot 2020-06-01 at 2 42 26 pm](https://user-images.githubusercontent.com/1221575/83376626-3e51b780-a416-11ea-813d-d38b76c96651.png)

Craft CMS 3.4.22.1
Commerce 3.1.5

**Comment by lukeholder** [comment]
Looking into this now.

Renaming `Totals` to `All Totals` since it is a summary column that shows multiple totals.

Leaving the first `Total` as is, and the second one to `Total Price`. `Total Price` is different to `Total` as it also checks the `minimumTotalPriceStrategy` setting.

If you resave the order, does it update the total?

Label fixes: 639cbc6e5f21d84e054176a6fa849a16e0204b0e

**Comment by engram-design** [comment]
Thanks, and re-saving the order doesn't change anything.

**Comment by lukeholder** [comment]
```
{%  set commerce = craft.app.getPlugins().getStoredPluginInfo('commerce') %}
Version: {{ commerce.version }}
```

Using the above the version of Commerce was being reported as `dev-develop` and not a reaal version number due to composer.json configuration. Making sure to be on a real version number fixed the issue due to this order query logic for totals: https://github.com/craftcms/commerce/blob/develop/src/elements/db/OrderQuery.php#L973-L983
