### ISSUE TITLE
Cant delete an order status

### ISSUE THREAD

**Issue by futurestudios** [craftcms/commerce#1487]
Cannot delete an Order Status

In the CP Go to Commerce > System Settings > Order Statuses
/admin/commerce/settings/orderstatuses

I should be able to delete an Order Status with a small X on right?

**Additional info**
- Craft CMS : 3.4.22.1
- PHP version: 7.3.1.8
- Plugins & versions: Commerce LITE v3.1.7

**Comment by lukeholder** [comment]
You can delete an order status if it is not the last (default) order status and no current orders are assigned to this status as their current status. The `x` will no show up for these statuses. Move the orders to another status to allow deletion of the status.

The delete does not actually delete though, it soft deletes, so that order status history is preserved.
