### ISSUE TITLE
Delay in emails being sent out 

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#1513]
**Description**
I am using Mailgun to send out emails, and there seems to be an issue with the emails not being sent out as soon as an order is made. 

E.g.
Customer placed an order at: 11/06/2020 22:37
Mailgun logged the email as accepted and delivery at: 12.06.2020 07:25

Is there a reason for this delay? It seems to happen with all orders, but the time difference varies. Sometimes it can be a couple of minutes, other times it can be a few hours like the above example. 

Ideally, I would like the emails to be sent out as soon as the order is placed.

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

Assuming you are running Commerce 3 order emails are now sent via a queue job ([updated via this issue](https://github.com/craftcms/commerce/issues/1063)) to increase performance when completing an order.

There is [information on order emails and the queue](https://docs.craftcms.com/commerce/v3/upgrading.html#order-emails) in the upgrade docs surrounding this update.

Hope this helps, thanks.

**Comment by j-greig** [comment]
I am still experiencing this issue on Commerce 3.2.14 (Mailgun to send emails), will create new issue but just flagging here in case helpful.

**Comment by joneslafuente** [comment]
Hi. A bit late to the party on this one I know but I only have 2 clients who use Commerce, all my others using Craft 3 or 4 only. I have updated one client to Craft 3/Commerce 3 recently and all seemed to be working ok. They are a small UK vineyard and sell only in the UK and only have 3 products, so very much small scale and an easy checkout process. Until they discovered emails are not being sent as before the upgrade. I appreciate the move to a queue is something that was needed but in this case a small site with a simple checkout is now failing the client as they don't see the order confirmation and the client is not getting the confirmation email. I cannot expect the client to login just to have the emails send. Tested and this does work but is not an answer for them, small workforce, busy running their business. Only needed to update everything because of UK banks and 2FA. 

Have tried the AsyncQueue plugin and that doesn't work. The emails and the rest of the queue just stall. Emails send when I login and send fine from the order age in the CP. Is just the automatic process on completing and order where it fails...

Any suggestions? I am not a developer, more a designer using Craft as it is better for my clients.

Thanks

Brian

**Comment by nfourtythree** [comment]
Hi

Thank you for your message.

As you mentioned we moved the emails to the queue for better performance. I understand from your perspective on your project it would be acceptable to have the older system, but we need to be able to cater for all manner of projects.

Although from a while ago, here is a good article on queue running and how you can make it a robust experience: https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

Due to your project having low traffic there are some good suggestions in the article to make sure the queue is getting executed as often as required.

Hope this helps, thanks!

**Comment by joneslafuente** [comment]
I have left a message on the AsyncQueue thread as even when installed it just stalls, emails never sent until admin logs in.

I had read the article before and agree it covers a lot of options but not being a developer and not being familiar with cli and cron etc do not know where to start. Not sure if being on a shared hosting is restricting my options. I just have to tell me client why his site is not working (his words, not mine!) when it used to before the upgrade.

Need an idiots guide to cli and cron and get my hands dirty I guess...

Thanks

Brian

**Comment by nfourtythree** [comment]
Hi @joneslafuente 

Thank you for your response.

I would recommend reaching out on our [community Discord serve](https://craftcms.com/community) as there are plenty of super helpful people that will have tackled a similar thing to you. Also, it could be worth reaching out to a [Craft CMS partner](https://craftcms.com/partners) that would be able to help with a matter like this.

Thanks!
