### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1528]
In general the new order layout is a big improvement, however the allocation of space in the edit order view in the lineitems area is not great yet - products with long titles wrap, when there is miles of room for quantity, which really doesn't need it.

![image](https://user-images.githubusercontent.com/731309/85191164-34c6bb80-b301-11ea-8f40-282ac433ba05.png)

Also we _really_ need access to other fields on that main tab please!   E.g. order notes are now very hidden fro view by being on another tab, and I believe there's no JS option to shift them easily anymore (if there is - let me know!).  I know there is an open issue about this but it's really quite important as otherwise order processing people can and will miss things.

**Comment by lukeholder** [comment]
Thanks for the feedback on this - going to close the ticket because it is too general. Please make 2 tickets - one for spacing and one for custom field placement. The custom field placement options might improve in 3.5 with the new field layout editor.https://twitter.com/brandonkelly/status/1281759362743246850
