### ISSUE TITLE
Error using deleteAllLineItemsByOrderId if product has been trashed

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#1545]
**Description**

We're getting an error when using `deleteAllLineItemsByOrderId`, which seems to be being caused when a product has been deleted and is in an inactive cart. 

Our module attempts to remove all line items from the basket BEFORE a new product/line item is added:

```
$cart = CommercePlugin::getInstance()->getCarts()->getCart();
CommercePlugin::getInstance()->getLineItems()->deleteAllLineItemsByOrderId($cart->id);
```

Which then causes this error, if the line item it's trying to delete doesn't exist because it's been deleted from the CMS:

```
2020-06-30 15:19:19 [-][1][rn53s23l8da7a00gdd7urk37l6][error][yii\base\Exception] yii\base\Exception: No line item exists with the ID “8795” in /home/xxx/vendor/craftcms/commerce/src/services/LineItems.php:224
```

**Additional info**
- Craft version: 3.4.24
- Commerce version: 3.1.9
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7

**Comment by lukeholder** [comment]
@bymayo 

>Our module attempts to remove all line items from the basket BEFORE a new product/line item is added:

Trying to understand what you are trying to do. Do you want to empty the cart before you update an existing line item? The error makes sense since you just deleted the line item, and now its trying to update a line item it can not find.

You are calling a method that deletes the line items from the database, but it looks like you are also trying to update the line item you just deleted. Would it be enough to just empty the cart with:

`$cart->setLineItems([])`, then let those removed line items be deleted when the order saves?

More information would help.

**Comment by bymayo** [comment]
@lukeholder We've got a weird situation where we need to empty the basket, but only if it's a certain type of product. The reason is that only 1 can be ordered of that product, but other products can have multiple (Otherwise we'd just use Lite).

So we're running the below code to clear the cart:

```
         Event::on(
            LineItems::class,
            LineItems::EVENT_BEFORE_SAVE_LINE_ITEM,
            function(LineItemEvent $event) {
              if ($event->isNew) {
                   $cart = CommercePlugin::getInstance()->getCarts()->getCart();
                   $cart->setLineItems([]);
              }
            }
         );
```

Using `$cart->setLineItems([])` stops the error from happening, but seems to not clear the cart, as both line items still exist.

The product we're adding to the cart, isn't the same one that already exists in there (The deleted product)

**Comment by bymayo** [comment]
@lukeholder I've done more tests on this and it seems that it's not just trashed products, but all products. So if you try and add a product to the basket and call `deleteAllLineItemsByOrderId` before `lineItems` are saved, it throws the error.

But, I have found that if I roll back to 3.1.5, it works like it did before and removes the items from the cart.

Do you know of anything that could have changed between 3.1.5 and 3.1.10 that could have caused this issue? I can't seem to pin point it in the changelog!

**Comment by lukeholder** [comment]
```
         Event::on(
            LineItems::class,
            LineItems::EVENT_BEFORE_SAVE_LINE_ITEM,
            function(LineItemEvent $event) {
              if ($event->isNew) {
                   $cart = CommercePlugin::getInstance()->getCarts()->getCart();
                   CommercePlugin::getInstance()->getLineItems()->deleteAllLineItemsByOrderId($cart->id);
              }
            }
         );
```

This code deletes all line items from the database (with `deleteAllLineItemsByOrderId($cart->id);`) just before saving the line item (since you are using the `EVENT_BEFORE_SAVE_LINE_ITEM` event), so the error is expected, I am not sure how you never got an error before.

I need to understand better what you are trying to do:

> where we need to empty the basket, but only if it's a certain type of product.

How do you know what the current item being added to the cart is inside the event you are using? All line items are resaved on order save so the event you are using is running for every item in the cart.

Maybe you want to use the before save order event and remove the line items you no longer want in the cart? Or remove all line items from the cart when you detect the line item inside the `EVENT_BEFORE_ADD_LINE_ITEM` event?

**Comment by bymayo** [comment]
Ahh okay, that explains it. But yeah, we've never had the issue before and the site has been live for around 2 years! Haha.

It just became more obvious with one of the recent Commerce releases.

> Maybe you want to use the before save order event and remove the line items you no longer want in the cart? 

The code I give an example of was a broke down version, we're basically calling a service in the `EVENT_BEFORE_SAVE_LINE_ITEM` to then do the checks on what type of products exist in the basket, then it runs the `deleteAllLineItemsByOrderId` method if it matches.

If theres a simpler way of just emptying the entire basket (Even addresses if possible etc) then i'd love to know of it, within a plugin, rather than using `deleteAllLineItemsByOrderId`

**Comment by lukeholder** [comment]
I would add your code to the 'before save order event' - cant keep this open as a bug as the error is expected as explained above.

**Comment by iamtompickering** [comment]
@lukeholder I've just been experiencing the same issues as this. So I have been running:
```
         Event::on(
            LineItems::class,
            LineItems::EVENT_BEFORE_SAVE_LINE_ITEM,
            function(LineItemEvent $event) {
              if ($event->isNew) {
                   $cart = CommercePlugin::getInstance()->getCarts()->getCart();
                   CommercePlugin::getInstance()->getLineItems()->deleteAllLineItemsByOrderId($cart->id);
              }
            }
         );
```
And it always seems to error with `No line item exists with the ID “xxxxx”`. I am just looking to completely clear the cart so that users only have 1 item in their basket at a time. 

Any reason why it would be doing this? Is there no other way of clearing the cart via events?

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

This is because you are deleting the line item mid save. For line items that were already in the cart, they would have an existing ID, intercepting this process and deleting the line item just before it tries to save will cause the error as it is trying to update that line item's data (which now no longer exists due to your deletion).

A better option would be to catch the save of the order and adjust the line items as required. Below is some example code to explain:

```php
use craft\commerce\elements\Order;
use yii\base\Event;
...
Event::on(Order::class, Order::EVENT_BEFORE_SAVE, function($event) {
    $order = $event->sender;
    $lineItems = $order->getLineItems();
    if (empty($lineItems) || count($lineItems) === 1 || $order->isCompleted) {
        return;
    }

    // Code to decide which line item to keep
    $order->setLineItems([$lineItems[0]]);
});
```

It is worth noting that this will be triggered on every save of every order element so you will need to take this into account with your code (e.g. saving from the CP, webhooks, recalculations etc).

Hope this helps, thanks!

**Comment by iamtompickering** [comment]
@nfourtythree thanks for this, I've just tried implementing your code but it doesn't seem to be firing. 

I'm doing a test log within the log, but when I go to add a product to the cart on the front end, nothing is logged, so it looks like that event isn't firing when adding a product to the cart? Am I missing something here?!

Thanks,

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

That is strange I have used xdebug to step through this and it all worked as expected. I then updated the code to add log lines in as follows:

```php
Event::on(Order::class, Order::EVENT_BEFORE_SAVE, function($event) {
    $order = $event->sender;
    $lineItems = $order->getLineItems();
    Craft::getLogger()->log('Count: ' . count($lineItems), Logger::LEVEL_INFO, 'Line Items');
    if (empty($lineItems) || count($lineItems) === 1 || $order->isCompleted) {
        Craft::getLogger()->log('Nothing to do.', Logger::LEVEL_INFO, 'Line Items');
        return;
    }

    // Code to decide which line item to keep
    Craft::getLogger()->log('Remove other line items.', Logger::LEVEL_INFO, 'Line Items');
    $order->setLineItems([$lineItems[0]]);
});
```

I looked in the logs and found the following when I added the first product:

```
2022-01-24 09:06:39 [-][-][-][info][Line Items] Count: 1
2022-01-24 09:06:39 [-][-][-][info][Line Items] Nothing to do.
```

And then this when I try to add a second

```
2022-01-24 09:07:20 [-][-][-][info][Line Items] Count: 2
2022-01-24 09:07:20 [-][-][-][info][Line Items] Remove other line items.
```

What level were you logging at? For example were you logging at `info` but had `devMode` off?
