### ISSUE TITLE
Can't delete shipping category

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce#1551]
**Description**
I have 2 x shipping categories and cannot delete one of them.

The "default" status is assigned to the other shipping category — would anything else prevent me deleting it?

Error message in CP:
```PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ionacrawford_local`.`commerce_lineitems`, CONSTRAINT `commerce_lineitems_shippingCategoryId_fk` FOREIGN KEY (`shippingCategoryId`) REFERENCES `commerce_shippingcategories` (`id`) ON UPDATE CA) in /Users/james/Repos/ionacrawford/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /Users/james/Repos/ionacrawford/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()```

**Additional info**
- Craft version: 3.4.25
- Commerce version: 3.1.10

https://www.loom.com/share/5907adea9099456ab9f368e48f210603

**Comment by alexwybraniec** [comment]
I'm encountering this as well. Is there any update or manual solution to fix this?

**Comment by lukeholder** [comment]
This is because there are line items in orders which are related to this shipping category. We will need to move to archiving the shipping categories and not deleting them. If you are *still in development* and the line items are just test orders, you can use the new console command to clear out all orders/lineitems, customers, subscriptions, etc etc

`php craft commerce/reset-data`

This will allow you to modify the shipping categories again since none will be related to that category.

If you are in production, you will need to wait until we add an archive feature shipping categories and tax categories: https://github.com/craftcms/commerce/issues/1815

**Comment by bhuvidya** [comment]
In the meantime, you might want to look at why there is no "formal" error message that appears onscreen when the ajax call  fails. I had to drop into chrome devtools to pinpoint the issue.
