### ISSUE TITLE
 Manual Gateway Fails when Creating Orders in CP

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#1559]
**Description**
Have a client who wants to take orders manually via check, for example.

Trying to use the manual gateway in the CP. Have it enabled on the frontend as well (for good measure, if though it technically shouldn't need to be).

**To Reproduce**
1. Create a new order in the CP. Add some line items and hit update to properly update the total.
2. Try to make a payment using the manual gateway.
3. Gateway errors with ``There is no gateway or payment source available for this order.``

**Expected behavior**
Manual gateway should succeed.

I can mark the order as complete but the it still appears as unpaid. If I try to make a payment at that point, it fails as well.

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.10
- PHP version: 7.3+

**Comment by samhibberd** [comment]
Probably not, but I ran into this just the other day and it was because I had 'Only allow this gateway to be used for zero value orders?' enabled in the gateway settings.

**Comment by nfourtythree** [comment]
Hi @RitterKnightCreative 

As @samhibberd stated the only way I can replicate this issue is if you have "Only allow this gateway to be used for zero value orders?" check and are trying to manually complete a non zero value order.

Having that unchecked allowed me to manually make payments as normal.

Going to close this for now, please let me know if there is another way to replicate thigs.

Thanks.

**Comment by RitterKnightCreative** [comment]
@nfourtythree @samhibberd Bingo, thanks! 

I think what must have threw me was the phrasing... I missed the first word ("only")! 

A minor copy improvement might be something like:

`` Use this gateway for zero value orders only``

**Comment by samhibberd** [comment]
I would second that, until I ran into this issue I had thought that setting was to ‘allow zero value orders’.
