### ISSUE TITLE
Order emails using url function include admin path

### ISSUE THREAD

**Issue by antcooper** [craftcms/commerce#1566]
I have a twig template setup for my order confirmation emails. It was using the [url](https://docs.craftcms.com/v3/dev/functions.html#url) function so I didn't have to hardcode the domain, but I noticed when a user was having problems signing in, that the URL in the email includes the /admin path (which I've renamed for our site). 

e.g. {{ url('member') }}

Outputs as https://www.domain.com/admin/member

As the template is in the public template folder, I wouldn't expect this

**Additional info**
- Craft version: 3.4.23
- Commerce version: 3.1.7
- PHP version: 7.3
- Database driver & version: MySQL 5

Thanks

**Comment by lukeholder** [comment]
When we render the twig template we do put the twig rendering mode as 'site' and not 'cp': `$view->setTemplateMode($view::TEMPLATE_MODE_SITE);` This takes care of making sure you twig includes etc are coming from the right place.

But since since the [`url()`](https://docs.craftcms.com/api/v3/craft-helpers-urlhelper.html#method-url) function helper function that you are using looks to see if the current *request* (triggering the email) is a CP request (and not the mode as we set above) - then the only way for you to ensure you are getting a site url is to use the:

[`siteUrl()`](https://docs.craftcms.com/api/v3/craft-helpers-urlhelper.html#method-siteurl) twig function. You will need to switch to using that. Thanks.
