### ISSUE TITLE
Inconsistent Variable Type for Address ID in AJAX on Get Cart Response vs Get Customer Addresses Response

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1569]
**Description**
The variable type for the shippingAddressId and billingAddressId when requesting the cart from `/actions/commerce/cart/get-cart` with AJAX is an integer.

The variable type for the ids of the addresses when requesting customer address from `/actions/commerce/addresses/get-customer-addresses` with AJAX is a string.

This causes an issue when trying to compare the values with JavaScript making `===` result in false.

**To Reproduce**
How, and what happened?
1. Make a request to `/actions/commerce/cart/get-cart`.
2. Make a request to `/actions/commerce/addresses/get-customer-addresses`.
3. Compare the ids with `===`.
4. Comparison results in false.

**Expected behavior**
What did you expect to happen?
I expected the variable types to be the same since they are the same piece of data.

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.11
- PHP version: 7.4.7
- Database driver & version: MySQL 8.0.20

**Comment by nfourtythree** [comment]
Hi @simeon-smith 

Just checking you are referring to: https://github.com/craftcms/commerce/blob/develop/src/controllers/AddressesController.php#L223

Because that is a CP controller which is not designed to be called from the front end? Or is it that you are calling it from the back end somewhere?

Thanks.

**Comment by simeon-smith** [comment]
@nfourtythree, Yes that's the one I'm talking about. I am able to call it from the front end.

It returns JSON?

```
return $this->asJson([
            'pagination' => AdminTable::paginationLinks($page, $total, $limit),
            'data' => $rows,
        ]);
```

**Comment by nfourtythree** [comment]
Hmm, you shouldn't be able to call this from the front end as it requires the `commerce-manageOrders` permission: https://github.com/craftcms/commerce/blob/develop/src/controllers/AddressesController.php#L34

And I have just tried it and I am getting the appropriate error.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/7KumlwOy/Screenshot%202020-07-14%20at%2020.44.02.png?v=3cbaf67375b2e29c331bb8df0d427aff)

Are you logged in as an admin while you are testing this?

Thanks.

**Comment by simeon-smith** [comment]
Yes I am.

Is there another way to retrieve a customers addresses via AJAX?

**Comment by simeon-smith** [comment]
Also if the controller requires those permissions then can normal users not use `/actions/commerce/addresses/save` with AJAX?

**Comment by nfourtythree** [comment]
There isn't a specific endpoint for that at the moment because it requires some thought on how we would deal with authentication for an endpoint like that. We can't just have an ID passed as it would be easy for someone to guess the next number and have access to sensitive data.

Your best option here is to create your own controller or twig template to do what you require. Taking into account the point above.

To save a customers' address we have the endpoint `commerce/customer-addresses/save` which is designed for front end use.

This can be seen in the [save address form in the example templates](https://github.com/craftcms/commerce/blob/develop/templates/shop/customer/addresses/edit.html#L22).

Thanks.

**Comment by simeon-smith** [comment]
For anyone else needing this, I created a simple endpoint for myself like so.

```
{% header "Content-Type: application/json; charset=utf-8" %} 
 
{% if currentUser %}
    {% set addresses = craft.commerce.customers.customer.addresses %}

    {{
      {
        success: true,
        message: addresses|length ? "Customer addresses successfully returned." : "No addresses for this customer.",
        addresses: addresses
      }|json_encode|raw 
    }}
{% else %}
  {{ {
    success: false,
    message: "Not logged in."
  }|json_encode|raw }}
{% endif %}
```
