### ISSUE TITLE
Tax validation against EU Tax ID

### ISSUE THREAD

**Issue by cole007** [craftcms/commerce#1596]
**What are you trying to do?**

The validator assumes a correct format for the tax and the country iso code to prepended to the ID. 
Many customers don't fill this out correctly, often using special characters to space out their ID (eg `8077.77.195.B01` instead of `NL807777195B01`).

This places onus on the user to know and enter this in the correct, predefined format. Of course this could be resolved with some front-end trickery but also assumes the Tax Id being stored in a format that the validator requires rather than the customer recognises.

**What's your proposed solution?**

As part of the [tax adjuster validation method](https://github.com/craftcms/commerce/blob/master/src/adjusters/Tax.php#L332) non-alphanumeric characters are removed and if not present the ISO code is added to the ID being validated. This value is not stored, simply used as part of the validation method.

For example, instead something like:

```
private function _validateVatNumber($businessVatId, $countryIso)
    {
        try {
            $cleanTax = preg_replace("/[^A-Za-z0-9 ]/", '', $businessVatId);
            if ($cleanTax !== '' && strpos($cleanTax,$countryIso) === false) {
                $businessVatId = $countryIso . $cleanTax;
            }
            return $this->_getVatValidator()->validate($businessVatId);
        } catch (Exception $e) {
            Craft::error('Communication with VAT API failed: ' . $e->getMessage(), __METHOD__);

            return false;
        }
    }
```

**Comment by lukeholder** [comment]
If we are validating the number with an API, I would expect the same valid number to be saved on the address. Otherwise we would have validated a number that is not really a valid VAT ID.

Would rather developer add front end validation, and also add a VAT business ID format validator to the address model.

I don't think the VAT ID format is not consistent though? (length etc) so leaving it with developers to do that validation as recommended above (front end, and address validation), and leave the vat validator API to only deal with validating them as a "real" VAT ID.

If there is a universal format validator you can come up with for a VAT ID, happy to look to add it to the address validator as an optional setting. (Make a new ticket/PR with that).

Thanks
