### ISSUE TITLE
Add ability to orderBy onSale

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/commerce#1604]
**What are you trying to do?**
I'm fetching variants with the ElementAPI and want to put the items witch are on sale first.

**What's your proposed solution?**
Add something like: `$criteria['orderBy'] = 'onSale DESC';` or `$criteria['orderBy'] = 'hasSales DESC';`

**Comment by lukeholder** [comment]
Hi @TomDeSmet This is something that will require 2 queries at the moment. A query for on sale, and not on sale.

We hope to make this possible when we pre-generate all sales prices into tables that make it easier to join the calculated prices into. This issue can be closed since it is covered within this issue: https://github.com/craftcms/commerce/issues/1041
