### ISSUE TITLE
Ability to disable the purge of orphaned addresses

### ISSUE THREAD

**Issue by mklishevych** [craftcms/commerce#1627]
**What are you trying to do?**
Exclude `Plugin::getInstance()->getAddresses()->purgeOrphanedAddresses()` from the garbage collection process.

**What's your proposed solution?**
New setting similar to `purgeInactiveCarts`, e.g. `purgeOrphanedAddresses` which would be true by default for backward compatibility.

**Additional context**
Due to the business specifics, we need to have more than just one shipping address. Sometimes it's up to 10 addresses. Anyways, current garbage collection process deletes orphan addresses if address is neither of the following:
- billing address
- estimated billing address
- shipping address
- estimated shipping address
- customer address
- store location

None of these work in our case. So our current solution is to simply disable garbage collection by setting probability to 0.

**Comment by lukeholder** [comment]
Hi

You say:
> Sometimes it's up to 10 addresses.

Where are those addresses related to? Seems funny to have an address that you do not know who or where it belongs to?

**Comment by mklishevych** [comment]
They are related to the order itself through a custom table (orderId, addressId).

**Comment by lukeholder** [comment]
Ah OK. Turning off orphaned addresses deletion totally would mean a huge number of addresses that never get cleaned up.

I think it would be better for you to hook into the orphaned address logic and skip addresses that you want to keep.

Adding it to the list.

**Comment by mklishevych** [comment]
Agree, that sounds like a better way of doing it. 

Thank you!

**Comment by jamiepittock** [comment]
Hey @lukeholder, we have a need for this too. 

We have a custom element type for schools - these are organisations we treat as customers, just not at the individual level. Schools have their own billing address. During checkout, if a user is related to a school, we automatically use the school's address as the order's billing address.

This is a site that's only just being updated for Craft 3 / Commerce 3 so this purging hasn't affected us before.

We could save the school's address in our own records but until now it's been a convenience to be able to hook into Commerce's address model.

**Comment by engram-design** [comment]
I've just hit this issue from a Commerce 2 upgrade.

We've got a unique client that needs to store the shipping address per line item, because each line item needs to have a different delivery address. As such, the addressId is serialised against a line item, instead of against the order. From what I can tell, this will trigger this query because it's not related to an order, instead a line item.

It's caused us a **lot** of headaches with addresses just suddenly being deleted (not even firing the before/after deleted events to catch it) and means we've had to either restore addresses from backups, or restore them by hand, before we could monkey-patch the removal of this purge event.

Personally, I'd like to see a setting to opt-out, or modify the query.

**Comment by nfourtythree** [comment]
@engram-design as a temporary solution if the addresses are stored per line item could you not simply store the serialized address in the line item snapshot instead of just storing the ID? Or attach them to a "ghost" user?

**Comment by engram-design** [comment]
Yep that’s actually what we do, we store both the serialised address info and addressId, because we want to save addresses for people to pick from again. It also allows them to manage them at their account level. Fortunately that’s meant the address information is “backed up” in the line time options, so we’ve been able to recreate the address.

For now, just rolling with a fork that disables it. If I get time, I’ll submit a PR.

**Comment by lukeholder** [comment]
Added the `EVENT_BEFORE_PURGE_ADDRESSES` event

```
Event::on(
    Addresses::class,
    Addresses::EVENT_BEFORE_PURGE_ADDRESSES,
    function(PurgeAddressesEvent $event) {
        // @var Query $addressQuery
        $addressQuery = $event->addressQuery;
        // Add an `$addressQuery->andWhere(..)` to change the addresses that will be purged query
        // $event->addressQuery = $addressQuery
    }
);
```

You can also set `isValid` on the event to false to stop all address purging.

**Comment by engram-design** [comment]
Thanks Luke, champion!
