### ISSUE TITLE
Move "store settings" in under "system settings".

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1681]
Move **store settings** in under **system settings**. https://p109.p1.n0.cdn.getcloudapp.com/items/7KuL6Ql1/Image%202020-08-27%20at%205.48.01%20PM.png?v=6c83cee36351824f5dd9add16cafc31f

**Additional context**
Store settings are rarely used more than when setting the store up so for me its annoying its there as part of normal nav items like settings, products, orders etc.
In addition to that I can rarely remember which settings I need to click on to find the normal settings. I know it says store settings vs system settings but still I find myself clicking the wrong one first.
Third reason is that I find having 2 settings items odd. In Woocomerce there is 1 settings and then tabs after that.

**Comment by bossanova808** [comment]
I agree, and given the naming can never really remember what is where anyway, so am just about always ending up clicking on both to find things...

**Comment by lukeholder** [comment]
"Store Settings" are things that are not stored in the project config and we expect store admins to change in production.
This will make more sense when we introduce multi-store functionality.

"System Settings" are only things stored in the project config, and it was much easier for now to make that it's own section so that developers to know everything there is is affecting the project config.

Will close this ticket but, please track under #37
