### ISSUE TITLE
Add actions for better headless support.

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/commerce#1682]
**What are you trying to do?**
I'm building a webshop with vue.js. While getting and setting the cart works like a charm, i'm missing this methods:

- Getting the customer address book.
- Getting a customers past orders.
- Getting the Payment Form HTML

This would be very convenvient when building headless shops.

**What's your proposed solution?**
Adding the necessary methods to the controllers.

**Comment by nfourtythree** [comment]
Hi @jan-thoma 

We have just pushed an update that will be included in the next Commerce release.

The update includes two new endpoints:

- `commerce/customer-addresses/get-addresses` for retrieving the current customer's addresses.
- `commerce/customer-orders/get-orders` for retrieving the current customer's previously completed orders.

Hopefully, you will find these useful in your project(s).

We are unable to provide an endpoint for the payment form HTML. This is because some gateways provide custom JavaScript when calling the payment form HTML. There is no ideal way to pass all of that back within an ajax call, therefore we recommend taking looking at what is required for the gateway(s) you are using and implementing that specifically in your project.

Thanks!
