### ISSUE TITLE
Calling undefined methods in example templates

### ISSUE THREAD

**Issue by timeverts** [craftcms/commerce#1722]
**Description**
There are some invalid Twig method references in `example-templates/buy/index.html`.

```twig
        <div class="text-grey text-right">
            Includes {{ cart.getTotalShippingCostAsCurrency }} shipping and
            {% if cart.getTotalTax() %}
                {{ cart.getTotalTaxAsCurrency }} taxes.
            {% endif %}
            {% if cart.getTotalTaxIncluded() %}
                {{ cart.getTotalTaxIncludedAsCurrency }} included taxes.
            {% endif %}
        </div>
```

The methods ending in `AsCurrency` do not exist on the order element.

Perhaps this is meant to be:
```twig
        <div class="text-grey text-right">
            Includes {{ cart.getTotalShippingCost()|commerceCurrency(cart.currency) }} shipping and
            {% if cart.getTotalTax() %}
                {{ cart.getTotalTax()|commerceCurrency(cart.currency) }} taxes.
            {% endif %}
            {% if cart.getTotalTaxIncluded() %}
                {{ cart.getTotalTaxIncluded()|commerceCurrency(cart.currency) }} included taxes.
            {% endif %}
        </div>
```

**Additional info**
- Craft version: 3.5.4
- Commerce version: 3.2.4
- PHP version: 7.1.22
- Database driver & version: mysql 5.6
- Other Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @timeverts 

Thank you for bringing this to our attention.

There was just a typo in the reference to the property should be `totalShippingCostAsCurrency` instead of `getTotalShippingCostAsCurrency`.

The `*AsCurrency` attributes have taken over from using the `commerceCurrency` filter. It basically does the same job, taking the cart's currency and producing the correct output.

Thanks!
