### ISSUE TITLE
Variant stock number - do not allow negative values

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1780]
I noticed that user can enter negative number into variant stock field and such variant can be saved without any errors.

**Comment by lukeholder** [comment]
Thanks for the request. We need to allow negative stock at the moment since our system can not prevent a race condition to allow the last item is stock to be purchased by 2 people at the same time. This allows a store owner to know when something has been over-ordered.

When we move to a proper #44 system this will be resolved.

**Comment by lukeholder** [comment]
See #44
