### ISSUE TITLE
If product related to line item was removed, automatically remove this line item from cart

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1803]
Today I removed product from DB and by accident, this product was also added to shopping cart earlier. 
This caused cart page to break, because `lineItem.purchasable` became null and template tried to access properties of purchasable like `lineItem.purchasable.price`.
I think it would be logical to automatically remove all line items from cart if its product was deleted.

**Comment by lukeholder** [comment]
When you delete a product/variant in the control panel it will automatically remove the line item from the cart when then order is recalculated. In the future you should try to delete the product that way. 

Accessing properties on the purchasable should be guarded against anyway in your code since a purchasable/product  could be deleted after the order is complete also, so the purchasable could go missing at anything.

For this reason we introduced the snapshot on the line item. This stores a snapshot of the product/variant data in case the item is deleted. (Also price could change for the purchasable, so you should get price from the line item anyway: `lineItem.salePrice`)

You can guard for a null in twig like this: `lineItem.purchasable.price ?? '0.00'`

If you wanted to get the price from the snapshot you could do this:

`lineItem.snaphot.price` this will work even if the purchasable was deleted. 

Hope that helps.

**Comment by piotrpog** [comment]
Thanks for explaining the concept of snapshot to me, it was really helpful.
