### ISSUE TITLE
Control panel's CSS files are loaded in Commerce's e-mail previews

### ISSUE THREAD

**Issue by mdominguez** [craftcms/commerce#1950]
**Description**
When previewing e-mails in Commerce's E-mail previews, the control panel's CSS files are being loaded.

**To Reproduce**
1. Commerce > System settings >  E-mails > Create one and click the 'Preview' button
2. See that in the source code unnecessary CSS files are loaded which interfere with the layout of the coded e-mail template.

**Expected behavior**
Don't load these CSS files as they don't add value here?

**Additional info**
- Craft version: 3.5.17.1
- Commerce version: 3.2.13.2
- PHP version: 7.1
- Database driver & version: / 
- Other Plugins & versions: /

**Additional context**

**Comment by nfourtythree** [comment]
Hi @mdominguez 

I have just tried to replicate this issue locally with the latest versions of Commerce and Craft and I can't see the issue you mention.

Could you take a screenshot of the network tab in dev tools where it shows the CSS file loading?

Have you tried reducing your email template to something super simple like below to see if the issue persists?

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email</title>

    <style type="text/css">
        * {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        }
    </style>
</head>
<body>
  Email body
</body>
</html>
```

Thanks.

**Comment by mdominguez** [comment]
[view screenshot](https://share.getcloudapp.com/bLu075xW)

**Comment by nfourtythree** [comment]
Hi @mdominguez 

Thank you for the screenshot.

What do you have you `siteUrl` and `cpTrigger` set to in your config?

Thanks

**Comment by nfourtythree** [comment]
Also @mdominguez, could you try disabling all other plugins/custom modules and see if that makes a difference.

Thanks!

**Comment by mdominguez** [comment]
Hi @nfourtythree 
Sorry for the late reply, a deadline had my priority the last 2 weeks.

I tried disabling the plugins 1 by 1 and found that the issue occurs only when this plugin is installed: [Slugs equal title](https://plugins.craftcms.com/slug-equals-title)

Hope this helps!

**Comment by nfourtythree** [comment]
Hi @mdominguez 

The issue here is that the "Slugs equal title" is loading their asset (which depends on the CP asset) on every CP request: https://github.com/internetztube/craft-slug-equals-title/blob/master/src/SlugEqualsTitle.php#L31

This means it will load on every CP page which has the potential to cause issues, not only to Commerce but other plugins as well.

I will post an issue on the repository and close this one.

Thanks for highlighting this!

**Comment by mmikkel** [comment]
> This means it will load on every CP page which has the potential to cause issues, not only to Commerce but other plugins as well.

Definitely a case to be made for plugins to be smart about when to register their asset bundles, but "page" is the operative word here. 

The reason why any registered CSS/JS is output for the email preview is that Commerce uses [`View::renderPageTemplate()`](https://github.com/craftcms/cms/blob/develop/src/web/View.php#L440) to render the email template. As per the source code, that method is meant to render ["a Twig template that represents an entire web page"](https://github.com/craftcms/cms/blob/develop/src/web/View.php#L429), which I'm not sure an HTML email would qualify as?

Additionally, [the actual email sendout](https://github.com/craftcms/commerce/blob/develop/src/services/Emails.php#L740) uses [`View::renderTemplate()`](https://github.com/craftcms/cms/blob/develop/src/web/View.php#L388), meaning that the preview and the actual emails have the potential to render differently.

Is this intentional, or should the email preview use [`View::renderTemplate()`](https://github.com/craftcms/cms/blob/develop/src/web/View.php#L388) instead?
