### ISSUE TITLE
Extend Product Type management permissions to Order Line Item SKU Search field

### ISSUE THREAD

**Issue by stevenjwright** [craftcms/commerce#2065]
**What are you trying to do?**
A User Group is set up, with restricted access on 'Manage X Product Type' permissions. 
When a user from that User Group goes to Create an Order from the CP, the Products available to search on will allow them to choose other product types not selected in their Product Management permissions. 

**What's your proposed solution?**
MVP could be for the same permission set to extend over to Creating/Editing an order from the CP though this could have other unintentional impacts depending on use case. 

Other suggestion would be granular control over what product types a CP User could add to an order. 

**Additional context**
Use Case here is in relation to an project in the works using a  multi-site workaround where Users are granted 'Manage' permissions on Product Types to dictate what they can/can't access. The problem comes when they wish to create an order in the CP, the Line Item search field will display all products of all product types.

**Comment by pdaleramirez** [comment]
#174 - Related enhancement.

**Comment by lukeholder** [comment]
@stevenjwright The permission to edit the product, is not related to the permission to edit the order and add products to the cart.

You are really hitting this due to a multi-site/multi-store workaround which we can't support just yet, but as @pdaleramirez mentioned we are working on improved permissions for Commerce 4 as well as Multi-Store support, so the use case will be met in that way.
