### ISSUE TITLE
Shipping zones Zip Code Condition: Data truncated

### ISSUE THREAD

**Issue by goraxan** [craftcms/commerce#2069]
**Description**
After entering and saving a long zipcode list (10k++ codes) we've found that MySQL is truncating data due to the column type being `TEXT` without any error.

**Workaround**
Manually alter the column type of `commerce_shippingzones.zipCodeConditionFormula` to `LONGTEXT` fixes the issue.

**Expected behavior**
I expect the data not to be truncated, or at least show an error to the user warning about it.

**Additional info**
- Craft version: 3.5.14
- Commerce version: 3.2.15.2
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.20
- Other Plugins & versions:

**Additional context**
This was already discussed in https://github.com/craftcms/commerce/issues/1138 and the proposed solution was to change the column type from varchar(255) to text

**Comment by lukeholder** [comment]
You are pasting in over 10k lines of code in that field? Do the codes have any pattern to them where you could use regex?

**Comment by goraxan** [comment]
Unfortunately not, since they are arbitrary.

**Comment by Mosnar** [comment]
@goraxan @lukeholder This doesn't seem like it's currently possible in the sandboxed template field, but perhaps you could create a tag group in globals with all your zipcodes and then match based on that instead of storing all the data in the template? This would require exposing the `craft` variable in the field, which is probably not a great idea, so I would imagine it would be best if you had to enable this via an event in a custom module or config setting.

```twig
craft.globals().getSetByHandle('commerceSettings').zipCodes.title(zipCode).exists()
```

**Comment by lukeholder** [comment]
We can't support or encourage use like this. I have gone ahead add added better validation https://github.com/craftcms/commerce/commit/323fd24df321e603354b8ab0b68bf08ae4c19491 so that the developer is aware when submitting the formula and no data is truncated when submitting.
