### ISSUE TITLE
Incorrect qty on line item in EVENT_POPULATE_LINE_ITEM

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#2152]
**Description**
We have to apply some additional charges based on certain conditions. For example, if a user chooses the passivation option, we need to add an additional $150 for that line item (regardless of quantity)

To do this, I was hooking onto the `EVENT_POPULATE_LINE_ITEM` event. But, it looks like the `qty` value for the line item is always 1 regardless of whether you submit a different `qty` value

**To Reproduce**
Create a simple add to cart form:

```twig
<form method="post">
    {{ csrfInput() }}
    {{ actionInput('commerce/cart/update-cart') }}

    <div>
        <label for="qty">Qty</label>
        <input type="number" name="qty" id="qty" value="1">
    </div>

    <div>
        <label for="purchasableId">Variant</label>
        <select name="purchasableId" id="purchasableId">
            {% for variant in product.variants %}
                <option value="{{ variant.id }}">{{ variant.sku }}</option>
            {% endfor %}
        </select>
    </div>

    <button type="submit">Add to Cart</button>
</form>
```

And then add an event:

```php
Event::on(
    LineItems::class,
    LineItems::EVENT_POPULATE_LINE_ITEM,
    function (LineItemEvent $event) {
        $lineItem = $event->lineItem;

        Craft::dd($lineItem);
    }
);
```

If you try and add an item to the cart with a qty of 10, you should see the `qty` in the dump is 1.

**Expected behavior**
I expected the `qty` value submitted in the add to cart form is the same as the value on the line item in the `EVENT_POPULATE_LINE_ITEM` event.

**Additional info**
- Craft version: Craft Pro 3.6.11.1
- Commerce version: 3.3.0.1
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.29

Let me know if there's any other info I can provide or if there's a better way to apply additional charges that I am missing. I was expecting that I should use an adjuster for this, but since you can only have an adjuster of `shipping`, `discount`, or `tax`, and you can only have one `tax` adjuster, I didn't really understand how I could use an adjuster for this functionality.

**Comment by pdaleramirez** [comment]
@davist11 
I looked into this and the `$lineItem->qty` is actually the overall quantity of the item in the cart. Let's say you have already added 2 Product 1 item to the cart. if you trigger the event the value of the `$lineItem->qty` would be 3.

You would always get value of 1 for every first added item to the cart, If you want to get the quantity value of the submitted data from the form you can use `$qty = Craft::$app->getRequest()->getBodyParam('qty');` to get the value.

**Comment by davist11** [comment]
Ah, hmm that's interesting. It's a little weird that the behavior is different from other line item events. If I switch to `EVENT_BEFORE_SAVE_LINE_ITEM` with an empty cart, and add a `qty` of 10, then the `qty` on that line item in the event is 10.

**Comment by joepagan** [comment]
>$lineItem->qty is actually the overall quantity of the item in the cart.

perfect just what we want

>You would always get value of 1 for every first added item to the cart, 

😭 

What is the benefit of qty being 1 when a user has added 10 when a line item is being added for the first time? 

If the reason is to identify a first time adding to basket scenario, that can been accomplished with `$event->isNew`?

So the best we can do here is:
```php
  $qty = Craft::$app->getRequest()->getBodyParam('qty')
  $theRealLineItemQuantity = $event->isNew ? $qty : ($qty + $lineItem->qty);
```

But this doesn't work when you reduce lineItem's quantity from 5 to 4... we need further logic to dynamically work with the post params for figure out the desired quantity? 
<img width="190" alt="image" src="https://user-images.githubusercontent.com/2337910/180490468-9afa5c44-0d78-49e2-be28-44b1926e033c.png">

It's getting pretty mental just to figure that out accurately unless I'm missing something?

Can `$lineItem->qty` just accurately report the desired quantity?

Can we ever reliably use `EVENT_POPULATE_LINE_ITEM` for quantity based price manipulation, or is `EVENT_BEFORE_SAVE_LINE_ITEM` the only event we can use for that?

Have I missed something obvious here? 
Craft's docs suggest using `EVENT_POPULATE_LINE_ITEM` for price manipulation, this behaviour should be highlighted more and I would argue that the docs should not suggest this event if quantities can impact price.
