### ISSUE TITLE
Calling an Order Element's getShippingMethod() no longer sets the least expensive option

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#2276]
**Description**
Calling an Order Element's `getShippingMethod()` method used to set the least expensive option for the order if one hadn't already been selected. This seems to have changed in 3.4.

The behaviour is [documented](https://craftcms.com/docs/commerce/3.x/extend/shipping-methods.html#getminrate).

> It’s important to note that calling getShippingMethod() (opens new window)will set the least expensive option for the order if one hasn’t yet been selected. This can lead to some confusion if you’re expecting it to represent an explicit choice from the user.

Was it an intended change or a bug?

**Comment by lukeholder** [comment]
@jamiepittock Can you confirm this is the case with 3.4.0.2 ?

**Comment by jamiepittock** [comment]
@lukeholder Yeah I've updated to 3.4.0.2. I think it's the change made to `craft\commerce\elements\Order::getShippingMethod()`  in this commit f307ccfa78b9bafce8421ee52c9b99159d483a74.

Previously it would fallback to the first available.

**Comment by jamiepittock** [comment]
@lukeholder I've realised it's not just that it no longer sets the least expensive option for the order if one hadn't already been selected.

Your [fix](7b39baf8fae3252b3f859db5a17a0a3fde5e43ed) yesterday means our custom shipping method is included again in `cart.availableShippingMethodOptions`. But even though we can now set the order's `shippingMethodHandle`, we still get null when calling `order.getShippingMethod()`, because that only looks for shipping methods in the database.

**Comment by bossanova808** [comment]
Am seeing this too (cheapest not selected), and can not actually set a shipping method on an order (using our custom shipping calculator)....and seeing this exception: https://github.com/craftcms/commerce/issues/2278 when trying to set a shipping option an order.

**Comment by jamiepittock** [comment]
> and seeing this exception: #2278 when trying to set a shipping option an order.

@bossanova808 Luke's fixed that part, but it's not been released yet - https://github.com/craftcms/commerce/issues/2277#issuecomment-883458102. 

Still waiting to hear about the other issues though.

**Comment by bossanova808** [comment]
ah ok - well, I had to roll back to get on with other things, will give it all another go soon.  (Today was at least a big improvement my first test a few days ago when hitting the shipping page pegged the CPU with Apache having a meltdown.....two steps forward one back and all that!)

**Comment by lukeholder** [comment]
@jamiepittock having the cheapest shipping method being set and returned with that method was documented because it was unexpected. It would not save the shipping method, just set it in memory, which was a little weird. 
We bit the bullet and have seen it as a bug and removed it but did not update the docs. Fixing those docs soon: https://github.com/craftcms/docs/issues/241

We have also updated our example templates to avoid using `order.shippingMethod.name` - we added a `order.shippingMethodName` cached value in `3.2.0` that can be used to get the name of the selected shipping method name and doing that in our examples.

About to release 3.4.0.3 that also fixes these:

https://github.com/craftcms/commerce/issues/2278
https://github.com/craftcms/commerce/issues/2279
