### ISSUE TITLE
Inconsistent status indicator spacing

### ISSUE THREAD

**Issue by mattstein** [craftcms/commerce#2511]
## Description

Commerce’s status indicators in table views and a few other places are visually inconsistent.

The _Status_ column, seen here in the Spoke & Chain demo, wraps the text beneath its indicator while the _Paid Status_ column does not:

<img width="803" alt="Screen Shot 2021-08-10 at 12 17 29 PM@2x" src="https://user-images.githubusercontent.com/2488775/128905088-bb0013d6-b94f-4c3a-bb6e-6d169cda95d3.png">

The two columns also have different amounts of white space between the indicator and its label. Here they are compared with the first column in a Craft _Entries_ listing:

<img width="486" alt="status-indicator-spacing" src="https://user-images.githubusercontent.com/2488775/128904755-6e1eef3c-d274-40b1-829d-b44015fca4b0.png">

The _Products_ listing displays its _Title_ field with the visual treatment I would expect:

<img width="803" alt="Screen Shot 2021-08-10 at 12 19 22 PM@2x" src="https://user-images.githubusercontent.com/2488775/128905578-7cbcf220-08dd-4566-903f-211bda1b7a5a.png">

The _Customers_ listing includes more space between the indicator and its label:

<img width="802" alt="Screen Shot 2021-08-10 at 12 22 35 PM@2x" src="https://user-images.githubusercontent.com/2488775/128905912-6f279613-84df-4d3d-a62f-d8dcb9fbb722.png">

## Audit

I think these look best when the indicator visually gets 6px of space between its rightmost extent and the beginning of its label, which seems to be what Craft’s listings and relationship field indicators get<sup>[1](#footnote)</sup>. (This also minimizes their pixel footprint, which seems like a two-fer.) With that in mind, here are the indicators I’ve seen in Commerce UI and whether they conform to that expectation:

### Matching Craft/Expected 👍

- **Products**  _Title_ column
- **Subscriptions** _Subscription plan_ column **(though column headings should also be Title Case)**

### Inconsistent/Unexpected 😐

@nfourtythree created [a branch](https://github.com/craftcms/commerce/tree/bugfix/fixed-status-spacing-issues) which looks like it resolves some of these. May not be exhaustive, but I sure tried:

| Location | Fixed in [`bugfix/fixed-status-spacing-issues`](https://github.com/craftcms/commerce/tree/bugfix/fixed-status-spacing-issues)? 
| -------- | --------
| **Orders** _Status_ and _Paid Status_ columns | ✓
| **Orders** _Order Status_ sidebar menu/filters | 
| **Orders** → (order detail) _Item_ statuses (for line items) | 
| **Customers** _User_ column | 
| **Promotions** Sales and Discounts _Name_ columns | 
| **Shipping** Shipping Methods, Shipping Categories, and Shipping Zones _Name_ columns | 
| **Store Settings** → **Countries & States** _Name_ column | 
| **Store Settings** → (Subscriptions) **Plans** _Name_ column | 
| **System Settings** → **Order Statuses** _Name_ column | ✓
| **System Settings** → **Line Item Statuses** → _Name_ column | ✓
| **System Settings** → **Line Item Statuses** → (new item) _Color_ dropdown | 
| **System Settings** → **Emails** → _Name_ column |
| **System Settings** → **PDFs** _Name_ column | 
| **Top Products** dashboard widget _Name_ column |

### Additional info

- Craft CMS version: 3.7.7, 3.7.8
- Craft Commerce version: 3.4.1

---

<a name="footnote">1</a>: Except in listings’ entry status dropdowns, which all get more spacing between the indicator and label:

<img width="218" alt="Screen Shot 2021-08-10 at 12 58 46 PM@2x" src="https://user-images.githubusercontent.com/2488775/128910945-f2e58103-1958-4691-a35e-39e50fa8e621.png">

**Comment by mattstein** [comment]
...and it’s come to my attention that the status dropdown’s indicators have their centers visually align with the wider icons beneath them while the labels all align flush-left—but I don’t believe there are any cases where Commerce mixes status indicators and icons with menu items. Take that however you will, I guess.

**Comment by nfourtythree** [comment]
@mattstein from your issue I have been through Commerce and made adjustments where things made sense.

In a number of places Commerce implements a status indicator followed by a word in the same way that Craft does for non-element items e.g. `<span class="status live"> Text` which is a common pattern. This comes with its own spacing and styling.

I think it would be a good idea if we are looking for consistency to solve this in Craft first and Commerce can then follow suit. This could be done with CSS or maybe a simple twig macro/component (or maybe a helper method in PHP).

Below is the table in the main body of the issue with updated statuses of what has been changed/what needs to be done.

| Location | Fixed in [`bugfix/fixed-status-spacing-issues`](https://github.com/craftcms/commerce/tree/bugfix/fixed-status-spacing-issues)? 
| -------- | --------
| **Orders** _Status_ and _Paid Status_ columns | Same as Craft
| **Orders** _Order Status_ sidebar menu/filters | Same as Craft 
| **Orders** → (order detail) _Item_ statuses (for line items) | ✓
| **Customers** _User_ column | ✓
| **Promotions** Sales and Discounts _Name_ columns | craftcms/cms#9704
| **Shipping** Shipping Methods, Shipping Categories, and Shipping Zones _Name_ columns | craftcms/cms#9704
| **Store Settings** → **Countries & States** _Name_ column | craftcms/cms#9704
| **Store Settings** → (Subscriptions) **Plans** _Name_ column | craftcms/cms#9704
| **System Settings** → **Order Statuses** _Name_ column | craftcms/cms#9704
| **System Settings** → **Line Item Statuses** → _Name_ column | craftcms/cms#9704
| **System Settings** → **Line Item Statuses** → (new item) _Color_ dropdown | Same as Craft
| **System Settings** → **Emails** → _Name_ column | craftcms/cms#9704
| **System Settings** → **PDFs** _Name_ column | craftcms/cms#9704
| **Top Products** dashboard widget _Name_ column | craftcms/cms#9704

As noted in the table there is a bugfix due for the admintable library that will help address the inconsistencies in some status styling within table layouts.
