### ISSUE TITLE
Shipping Rule (max weight) in Method does not get applied in checkout process 

### ISSUE THREAD

**Issue by hhentschel** [craftcms/commerce#2531]
### Description
i've set-up a shipping method and there a rule, that is should get applied if the Order Total Weight is max. 500g.
![image](https://user-images.githubusercontent.com/2101975/131988002-c9cdd95d-21e6-49b4-a0ea-e01b6b75b460.png)

(in the commerce setting, i have Grams (g) as the Weight Unit.)

in my cart i have an item, which has in the variant section 500g.
i use the basic commerce templates and when i go to the shipping.twig page, this shipping method does not appear.
(when i erase any number besides 0, the method appears).

i have a second rule in a second method, where i've set up a min weight of 501 and a max of 1000.
this method also does not get shown.

Also, when i open the Info icon on the rule, the weight gets displayed with 3 zeros after the dot/comma.
is this the right format anyway?

![image](https://user-images.githubusercontent.com/2101975/131988366-0eb9f116-400b-4411-b2df-517afc43e645.png)

### Steps to reproduce

1. creating shipping Method
2. create shipping rule
3. in there set max value to 500

### Additional info

- Craft CMS version: 3.7.4
- Craft Commerce version: 3.4.2
- PHP version: 7.4.22
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
- Entry relations | 1.0.5
- Expanded Singles | 1.1.4
- Feed Me | 4.3.6

**Comment by nfourtythree** [comment]
Hi @hhentschel 

Thank you for your message.

The weight conditions are matched as follows:

- when using minimum weight the total weight for the order must be greater than or equal to the value set ([see matching in code](https://github.com/craftcms/commerce/blob/develop/src/models/ShippingRule.php#L374))
- when using maximum weight the total weight for the order must be less than the value set ([see matching in code](https://github.com/craftcms/commerce/blob/develop/src/models/ShippingRule.php#L377))

We understand that this may not be too clear and currently have a [feature request](https://github.com/craftcms/commerce/discussions/2325) in place to address this.

As for your question regarding the decimal places shown. This is because the value can be a decimal value and there for that is the data that is actually stored.

Hope this helps, thanks!
