### ISSUE TITLE
Tax doesn't update when changing price of lineitem

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#2534]
If we manually change the price of a lineItem via the CP, it doesn't not have an affect on the tax. It appears the tax is still calculated on the original salePrice rather than the updated lineItem price in the CP.

**Comment by nfourtythree** [comment]
Hi @samuelbirch 

I assume you are talking about a completed order here? Completed orders are set to not recalculate automatically, this is to prevent unwanted things from happening e.g. newer discounts applied that weren't available at the time etc.

We are looking to how we can refine this on a more granular level and we have a feature request out there for recalculating adjustments only: https://github.com/craftcms/commerce/discussions/2394

At the moment you have two options, manually click recalculate (understanding the implications of this) or change the tax manually (we are also thinking about how we could make this easier for the store/customer service user).

Thanks!

**Comment by andykearney** [comment]
On a completed order, if a lineitem price has been changed, either by editing the lineitem price directly or by adding a discount adjustment, manually clicking recalculate doesn't adjust the tax figure. It just removes any/all adjustments leaving the tax figure as it was. 

Option 2 being manually change the tax isn't really feasible with 20 staff and 1k orders per month. We're struggling with this one.

**Comment by john-henry** [comment]
This maybe related https://discord.com/channels/456442477667418113/666747438794670140/892559611406733322

**Comment by john-henry** [comment]
@nfourtythree Would you be able to consider having another look at this one. Its happening for an uncompleted order too. 
If I remove tax from a line item via an adjuster the order total tax is not updated.

Do you want me to break it down into a more vanilla example

**Comment by nfourtythree** [comment]
@john-henry correct it is on the Line Item price

**Comment by john-henry** [comment]
@nfourtythree ok so this is interesting. If I dump out $newTaxTotal on the order page I get 0
But if I go back to order index and turn on Total Tax column I still see a tax amount

https://share.johnhenry.ie/6quvOmWd

That's where the issue was. For all intensive purposes it was doing the same in my code as yours but the Total tax for the Order was indeed not updating.

Can you turn on the Total Tax for your active order index and let me know if it is 0 or there is tax?

**Comment by nfourtythree** [comment]
Hi @john-henry 

It is a bit difficult giving a solution without knowing the full brief of what data you have, what you are trying to achieve and what caveats there are.

Trying to do things the way you are at the moment is a bit awkward due to the fact all the calculations have already happened by the time you are then trying to remove some of the information. I would maybe try resaving the order and just make sure in your logic in the after save event you aren't getting into infinite loops.

The more ideal way for this could be to create your own tax adjuster that extends the built-in tax adjuster, that way you would be able to override something like the `adjust` and/or `getTaxRates` to exclude the rate you don't want to apply.

Using the `OrderAdjustments::EVENT_REGISTER_ORDER_ADJUSTERS` event you could then register your tax adjuster and remove the core adjuster from `types`. This would probably be a more clean approach as then everything is happening when it should be.

Hope this helps.
