### ISSUE TITLE
Line item not removed from cart if available quantity changes to zero

### ISSUE THREAD

**Issue by codyjames** [craftcms/commerce#2536]
### Description
It would be nice if items with zero available quantity would get removed from any cart that contain them. It _seems_ like that is the intent based on: https://github.com/craftcms/commerce/blob/9f2414241d997fd46b56dcfe80cfb11bda34f842/src/elements/Order.php#L1768-L1780

However, there is also an Cart Error that happens here: https://github.com/craftcms/commerce/blob/9f2414241d997fd46b56dcfe80cfb11bda34f842/src/elements/Variant.php#L799 which blocks the Cart Notice from happening due to this:
https://github.com/craftcms/commerce/blob/9f2414241d997fd46b56dcfe80cfb11bda34f842/src/elements/Order.php#L1725-L1728

### Steps to reproduce

1. Add something to your cart
2. Do something to make the stock/qty be zero (reduce the stock in the CP, for instance).
3. Try to progress the cart.

### Additional info

- Craft CMS version: 3.7.6
- Craft Commerce version:  3.4.1

**Comment by codyjames** [comment]
As it stands, a user has to either remove the item from their cart manually, or we'll have to build some code to remove it for them. If the commerce codebase is behaving as-designed and as-expected, I can work around this.

**Comment by AugustMiller** [comment]
_Originally drafted 2021-09-15:_

Cody and I talked this afternoon, and I'm inclined to agree that there's an issue with the location of this logic.

By the time the Order is recalculated (`Order::afterSave()`), validation has already happened, meaning `LineItem` models have bubbled their quantity errors. Therefore, `$this->hasErrors()` prevents _any_ recalculation from happening.

Currently, the only place this logic will actually affect the cart is [during payment](https://github.com/craftcms/commerce/blob/9f2414241d997fd46b56dcfe80cfb11bda34f842/src/controllers/PaymentsController.php#L361-L364)—but maybe that's the intended behavior? As far as we could tell, this is the only place where recalculation happens _prior_ to validation.

We ended up hooking into the `Order::EVENT_BEFORE_VALIDATE` and eagerly validating `LineItem` models, then discarding ones with quantity errors (which was acceptable for that application, but wouldn't be for most others). The Order then "passed" validation (because it no longer cared/knew about the offending `LineItem`s), and saved as expected. In the process, we added our own `OrderNotice`, emulating the behavior of the `recalculate()` method.

Ultimately, we agreed that something was out of place, but didn't have a strong conviction about _what_…

Maybe this? 🙃 

https://github.com/craftcms/commerce/blob/9f2414241d997fd46b56dcfe80cfb11bda34f842/src/elements/Order.php#L1899-L1901

---

_Updated 2021-09-16:_

Talked again this morning, and ended up adapting the event responder to something like this, to better mimic the pre-payment behavior:

```php
Event::on(
    Order::class,
    Order::EVENT_BEFORE_VALIDATE,
    function (Event $event) {
        $order = $event->sender;

        // Don't apply to completed orders:
        if ($order->isCompleted) {
            return;
        }

        $order->recalculate();
    });
```

**Comment by pdaleramirez** [comment]
Fixed (#2560) Please update to the latest version.

**Comment by codyjames** [comment]
@pdaleramirez It seems to now remove things from the cart if they are no longer available (as expected), but it seems to not set any notices about that happening. So something just gets yoinked from the cart with no explanation.

**Comment by pdaleramirez** [comment]
> @pdaleramirez It seems to now remove things from the cart if they are no longer available (as expected), but it seems to not set any notices about that happening. So something just gets yoinked from the cart with no explanation.

Maybe it's worth creating a new issue for this.
