### ISSUE TITLE
Active Carts showing under Inactive Carts in Commerce Admin

### ISSUE THREAD

**Issue by antcooper** [craftcms/commerce#2610]
### Description
Since updating to Commerce 3.4.7, any active cart sessions are showing in the *Inactive Carts* section of Commerce Admin. the *Active Carts* section has 0 rows.

### Steps to reproduce

1. Create a test order on the front-end by adding an item to cart.
2. In the Admin, look for the order in Active/Inactive Carts sections

### Additional info

- Craft CMS version: Craft Pro 3.7.20
- Craft Commerce version: 3.4.7
- PHP version: 7.3.31
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Stripe for Craft Commerce 2.4.0

**Comment by jlachancekffein** [comment]
If it can help, the problem seems to come from ```craftcms/commerce/src/services/Carts.php -> getActiveCartEdgeDuration()```

The problem is :
```php
return Db::prepareDateForDb($edge);
```

The solution is to use the latest version of the code
```php
return $edge->format(DateTime::ATOM);
```

The problem seems to be related to timezone.

On our side, this bug is very problematic cause we use ```$customer->getActiveCarts();``` to retreive the latest customer carts. With this bug, nothing is returned cause the carts is considered inactive.

**Comment by lukeholder** [comment]
Fixed for next release
