### ISSUE TITLE
[4.x]:  Cannot set the address as primary address

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2762]
### Description
In address modal there are checkbox to set the address as primary billing or primary shipping but even after we check these the address is not saved as primary address.

### Steps to reproduce

1. Add the address fields to user.
2. Select your profile and click on address field to add new address.
3. Fill all require data and  put also as primary shipping or primary billing address.
4. Save the address.

### Expected behavior
- The address should be added as primary billing or shipping.

### Actual behavior
- The save success, not error, but if we click again the save address, it doesn't marked as primary billing or shipping address.

### Craft CMS version

4.0.0-beta.3

### Craft Commerce version

4.0.0-beta.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @aodihis 

Thank you for reporting this. It turns out they were saving as the primary but the checkboxes were not being set properly to identify that, that was the case.

We have pushed up a fix which will be included in the next beta release.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "4.0.x-dev#2ab02567809ca55797dc31a4d95dc8e3e96acca6 as 4.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 4.0.0-RC1 is out now with that fix.
