### ISSUE TITLE
[4.x]: Cannot open the address sidebar on  order

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2817]
### Description
After have the order and set the address, then save it. Later if we click edit address, the sidebar for editing address not oppened.

### Steps to reproduce

1. Create an order
2. Add the customer and set the billing or shipping address
3. Save it.
4. After save open that order than try to click the edit address.

### Expected behavior
in step 4 the sidebar for editing address will open 

### Actual behavior
Nothing happen

### Craft CMS version

4.02

### Craft Commerce version

4.0.0

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @aodihis 

Thank you for reporting. 

This was caused by a little bit of confusing UI. The addresses should have been showing in a "static" mode when you first load a completed order on the edit order page.

Clicking the "edit" button would enable edit mode and allow you to edit the addresses.

We have pushed an update that fixes the UI to make this apparent. It will be included in the next release of Commerce.

Thanks!
