### ISSUE TITLE
[4.x]: cart/update-cart controller doesn't return succes, errors or error keys when returning as JSON

### ISSUE THREAD

**Issue by Antimated** [craftcms/commerce#2933]
### Description

Doing a post request to the `cart/update-cart` controller with the headers `Accept: application/json` doesn't return the succes/error (and probably more) keys as the [docs describe](https://craftcms.com/docs/commerce/4.x/dev/controller-actions.html#with-json-request-header-2).

In commerce **3** the following data was returned for a successful update-cart response (notice the success key being present):
```
return $this->asJson([
      'success' => !$this->_cart->hasErrors(),
       $this->_cartVariable => $this->cartArray($this->_cart),
       'message' => $message,
]);
```

This is how it looks in commerce **4**:
**Success** (no success key):
```
return $this->asModelSuccess(
     $this->_cart,
     $message,
     'cart',
    [
        $this->_cartVariable => $this->cartArray($this->_cart),
    ]
);
```

**Error** (no error key):
```
return $this->asModelFailure(
    $this->_cart,
    $message,
    'cart',
    [
        $this->_cartVariable => $this->cartArray($this->_cart),
    ],
    [
        $this->_cartVariable => $this->_cart,
    ]
);
```

Not sure if this a bug or if the docs are inaccurate (or perhaps an mistake on my part)

### Steps to reproduce

1. Do a post request to `cart/update-cart` with 'Accept: application/json' headers
2. Inspect te json output to not have any success, errors or error keys.

### Expected behavior
Response should include a success, error and/or error key.

### Actual behavior
Screenshot of post request done with Axios
![Screenshot 2022-08-12 at 10 37 25](https://user-images.githubusercontent.com/2869409/184317495-51527be1-8505-4fe8-be0d-b027ff27e2e9.png)

### Craft CMS version

Craft Pro 4.2.0.2

### Craft Commerce version

4.1.0

### PHP version

8.1.5

### Operating system and version

Darwin 20.5.0

### Database type and version

MySQL 5.7.34

### Image driver and version

GD 8.1.5

### Installed plugins and versions

- Cookies: 4.0.0
- CP Field Inspect: 1.4.4
- Craft Commerce: 4.1.0
- Formie: 2.0.5
- Gift Voucher: 3.0.0-beta.2
- Knock Knock: 2.0.2
- Maps: v4.0.3
- MatrixMate: 2.1.0
- Position Fieldtype: 4.0.0-beta.3
- Ray: 2.0
- Redactor: 3.0.2
- Redactor tweaks: 3.0.0-beta.1
- SEOmatic: 4.0.7
- Super Table: 3.0.0
- Typed Link Field: 2.1.3-rc
- Vite: 4.0.2

**Comment by martyspain** [comment]
This is expected behaviour. Craft and Commerce 4 have changed how JSON responses are handled, so rather than returning a `success` key you need to check the status code of the response to determine whether the request was a success (status is `200`) or not (status is a`400`). There's a discussion on the change [here](https://github.com/craftcms/cms/discussions/8631) and I believe it was mentioned in the release notes, though I can't find that at the moment. It's covered in the [upgrade guide](https://craftcms.com/docs/4.x/extend/updating-plugins.html#controller-requests-responses) for plugins, which is where I was made aware of the change, but unfortunately it's not mentioned in the front-end upgrade guides for Craft or Commerce, which I feel is a bit of an oversight.

The Commerce 4.x docs for [controller JSON responses](https://craftcms.com/docs/commerce/4.x/dev/controller-actions.html#with-json-request-header-2) are out of date and show the old JSON response, but the Craft 4.x docs for [controller JSON responses](https://craftcms.com/docs/4.x/dev/controller-actions.html#with-json-request-header) are correct.

**Comment by nfourtythree** [comment]
Thanks for jumping in here @martyspain !

@Antimated I have made an issue over on the [docs repo](https://github.com/craftcms/docs/issues/413) to make some updates/fixes to the docs so this is more clear to people upgrading from a previous version of Commerce.

Thanks!
