### ISSUE TITLE
Store Location not saving

### ISSUE THREAD

**Issue by stovepot** [craftcms/commerce#302]
### Description
Store location for Australia | State: Victoria not saving when State is selected.
`Couldn’t save address.`

### Steps to reproduce

1. Settings
2. Store Location
3. Select State

### Additional info

- Craft version: Craft Pro 3.0.1
- PHP version: 7.1.0
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Craft Commerce: 2.0.0-beta.1.1

**Comment by lukeholder** [comment]
@stovepot Not able to reproduce on 2.0.0-beta.1.1 Can you send your logs to support@craftcommerce.com and reference this issue number, thanks.

**Comment by lukeholder** [comment]
Looking in your logs, I see a number of errors due to installing commerce with 2.0.0-beta.1 which had issues with its installer.

Can you follow these steps to fix your new installation.

If you upgraded a commerce 1 site do not follow these instructions.

In your case I am thinking it would be that commerce never installed correctly due to a bug in the 2.0.0-beta.1

You need to uninstall and remove the commerce plugin settings > plugins > commerce cog icon > remove plugin

If you get an error on uninstall (before removing) do the following:

- Uninstall any new plugins that depend on Commerce you have installed through the store, like a stripe or paypal gateway plugins.
- Delete all tables in the database starting with commerce_ (if any)
- Delete the commerce row in craft's plugins table.
- Goto settings > plugins > commerce cog icon > remove plugin
- Go back to the store and 'try' commerce again. which should install the 2.0.0-beta.1.2 which does not have the issues you are seeing.

Hope that helps.

The guzzle issue is due to a gateway plugin that uses the omnipay/omnipay package, we have moved off a dependance on
