### ISSUE TITLE
[4.x]: Discounts for Estimated Shipping Address

### ISSUE THREAD

**Issue by vandres** [craftcms/commerce#3034]
### Description

I am having a Variant discount, which is based on the shipping address

<img width="1201" alt="grafik" src="https://user-images.githubusercontent.com/1436383/202699204-19c5189c-9ce5-4c68-8919-d75e77705a06.png">
 
This discount works fine when being in the checkout. But I would like to disclose the price change already in the cart. No matter if the user is logged in or not. For that we have an IP-based user location recognition, which we use to set the estimated shipping address. In the cart itself, we use the shipping cost estimator from the Commerce example templates.

The problem is, that this discount doesn't show up in the line item adjustments, as long as it is only an estimated shipping address. Is there any way to bypass that restriction? We cannot create a real address at that point, since we have a lot of required fields.

### Steps to reproduce

1. Create a discount rule based on shipping address
2. Add a matching product to the cart
3. Set an estimated shipping address

### Expected behavior

I see (estimated) line item adjustments. Like it works for shipping

### Actual behavior

I see no line item adjustments

### Craft CMS version

4.3.1

### Craft Commerce version

4.2.2

### PHP version

8.1

### Operating system and version

MacOS, Debian Docker

### Database type and version

MariaDB 10.5

### Image driver and version

-

### Installed plugins and versions

```
  "require": {
    "craftcms/cms": "^4.2.0.2",
    "craftcms/commerce": "^4.1.0",
    "craftcms/commerce-paypal-checkout": "dev-develop",
    "craftcms/redactor": "^3.0",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-retour": "^4.1",
    "nystudio107/craft-vite": "^4.0",
    "php-http/curl-client": "^2.2",
    "putyourlightson/craft-elements-panel": "^2.0",
    "putyourlightson/craft-sprig": "^2.1",
    "sebastianlenz/linkfield": "^2.1",
    "spatie/craft-ray": "^2.0",
    "spicyweb/craft-neo": "^3.2",
    "typesense/typesense-php": "^4.8",
    "vaersaagod/geomate": "^2.0",
    "verbb/expanded-singles": "^2.0",
    "verbb/field-manager": "^3.0",
    "verbb/tablemaker": "^4.0",
    "verbb/wishlist": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "deployer/deployer": "^7.0",
    "yiisoft/yii2-shell": "^2.0.3",
    "roave/security-advisories": "dev-master"
  },
  ```

**Comment by lukeholder** [comment]
This is not possible at the moment. We don't have any ability for the discounts to be marked as estimated as that feature was only designed for use with shipping and tax adjustments.

You will need to collect the real shipping address and not use the estimated address fields on the order to get the discount to show up. This will also let you show real tax and shipping.

We are likely to deprecate the estimated addresses for use with shipping and taxes, since now in 4.0 addresses are stored directly on the address and not in the address book automatically, so a partial address could be saved to the order with custom validation rules to reduce the fields required on the address.

For example:

```
Event::on(
            Address::class,
            Model::EVENT_DEFINE_RULES,
            function (DefineRulesEvent $event) {
                $rules = $event->rules;
                if (in_array(Craft::$app->getRequest()->getPathInfo(), ['checkout/cart'])) {
                    $rules[] = ['countryCode', 'required'];
                    $rules[] = ['postalCode', 'required'];
                }
                $event->rules = $rules;
            }
        );
```

Would reduce the required fields on addresses on the the cart page to just countryCode and postalCode - which would allow you to submit a partial address.

Hope that helps.
