### ISSUE TITLE
[4.x]: EVENT_POPULATE_LINE_ITEM fires multiple times

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/commerce#3346]
### Description

I've been using EVENT_POPULATE_LINE_ITEM for a long time in Commerce 3 and I've recently upgraded to 4. However now EVENT_POPULATE_LINE_ITEM seems to fire at least 3 times when an item is added to the cart. Each is identical.

### Steps to reproduce
1. Add a module like this.

```php
Event::on(
  LineItems::class,
  LineItems::EVENT_POPULATE_LINE_ITEM, 
  function(LineItemEvent $event) 
  {
     if ($event->isNew) 
     {
       Craft::info($isNew, 'my-module');
     }
  }
);
```
2. Add an item to the cart.

### Expected behavior
A single log entry is created

### Actual behavior
Three log entries are created
```
2023-12-01 21:33:52 [web.INFO] [my-module] true {"memory":44893448} 
2023-12-01 21:33:52 [web.INFO] [my-module] true {"memory":45303680} 
2023-12-01 21:33:52 [web.INFO] [my-module] true {"memory":47529120} 
```

### Craft CMS version

4.5.11.1

### Craft Commerce version

4.3.2

### Installed plugins and versions

Gift Voucher 3.0.9

**Comment by lukeholder** [comment]
We have reduced the number of recalculations in recent releases of Commerce, but it's possible for the event to fire multiple times for various reasons, like if the recalculation needs to run again after a shipping method that is selected becomes disqualified due to order value etc. So the line item could be identical each time.

You need to make sure your event handler is able to handle deciding when to modify the line item again or if can skip making the modifications.
