### ISSUE TITLE
[4.x]: Removing existing variant title and resaving re populates the title with previously saved rather than failing validation as required.

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3384]
### What happened?

I'm not sure if this is by design, but it's caught us out a few time as we would expect it to throw an error as required?

I have testing in a fresh install of the latest commerce:

https://github.com/craftcms/commerce/assets/1846063/e644a791-b9cc-46c8-98c6-2b1e2c888fe3

### Craft CMS version

4.7.2

### Craft Commerce version

4.4.1.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Thank you for raising this, it appears you have spotted something that has been in existence since `2.0`.

We have pushed a fix for this which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#6a4669901e7bdd151fe77a196f7d1652aeb5333c as 4.5.0",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by samhibberd** [comment]
Awesome thanks!

**Comment by lukeholder** [comment]
4.5.1  is now out with this fix. Happy leap day!
