### ISSUE TITLE
[5.x]: After 4 -> 5 upgrade - `config/commerce.php` based settings not present in store project config

### ISSUE THREAD

**Issue by rob-c-baker** [craftcms/commerce#3632]
### Description

After install of both Craft 5 & Commerce 5, the docs [her](https://craftcms.com/docs/commerce/5.x/upgrade.html#multi-store) say "During the upgrade, Commerce copies each setting onto the new default/primary store, and saves them in [project config](https://craftcms.com/docs/5.x/system/project-config.html)", however, with the following in `config/commerce.php`:

```php
return [
  '*' => [
    'requireBillingAddressAtCheckout' => true,
    'requireShippingAddressAtCheckout' => true,
    'requireShippingMethodSelectionAtCheckout' => true,
    ...
  ],
  ...
];
```

The store project config in `config/project/commerce/stores/primaryStore-...yaml` shows only:

```yaml
currency: GBP
handle: primaryStore
name: 'Primary Store'
primary: true
```

When checking Commerce→ System Settings→ Stores→ Primary, that confirms the settings did not come across.

### Expected behavior

Config from Commerce 4 arrives in the Commerce 5 store project yaml.

### Craft CMS version

5.3.4

### Craft Commerce version

5.0.16

### PHP version

8.3.7

### Operating system and version

N/A

### Database type and version

MySQL 8.0.37

### Image driver and version

N/A

### Installed plugins and versions

Asset Rev	8.0.0
CKEditor	4.2.0
CP Field Inspect	2.0.2
Craft Commerce	5.0.16
Digital Download	3.1.1
Digital Products	4.0.0
Elements Panel	3.0.0
Minify	5.0.0
Navigation	3.0.3
PayPal Checkout for Craft Commerce	3.0.1
SEOmatic	5.1.1
Stripe for Craft Commerce	5.0.4.2

**Comment by rob-c-baker** [comment]
Hi @lukeholder any updates on this?

**Comment by lukeholder** [comment]
The settings were migrated in the DB so the store will be using those settings, but were not written to the project config.

I have [pushed](https://github.com/craftcms/commerce/commit/315e4cb962a1e50a3b48686fef95b2f6bf9778de) a fix for the original migration for the next release of Craft Commerce 5.x so that the project config gets written out during the migration.

If you have already upgraded you can manually enter the values from the old commerce.php file into your store settings:

![CleanShot 2024-08-28 at 21 19 31@2x](https://github.com/user-attachments/assets/30b51dd4-5c42-47fe-bc4b-ba4b79e3f987)

, then save the store in development and this will regenerate the store project config file, which you can then deploy.

Have you already upgraded?

**Comment by rob-c-baker** [comment]
Thanks for getting back to me.

Our commerce site has only been upgraded in non-production environments so far.

I did not see our settings on that screen in DEV - just the defaults, so I'm not sure if the fact a project config sync ran directly after migrations meant the DB settings got wiped out (i.e. `php ./craft up`).

It would be nice if all settings arrived in automatically to not have to manually compare them when the deployment hits production. It sounds like that's what's coming, so I'll hang on for that and re-run the upgrade from DEV onwards again.

Is there an estimate on a release date for the next version containing this?

**Comment by rob-c-baker** [comment]
Closing - latest version (I tried Commerce 5.1.0) fixed this. Thank you.

**Comment by lukeholder** [comment]
Glad you're sorted!
