### ISSUE TITLE
isDefault attribute of Variant Model outputs 1 and 0 instead of true and false

### ISSUE THREAD

**Issue by motorzen** [craftcms/commerce#371]
### Description
**isDefault** attribute of Variant Model outputs `1` and `0` instead of `true` and `false`

For context, I had code that did a test to apply a class of "default" for the isDefault product variant:
`class="{% if purchasable.isDefault=='true' %} default {% endif %}"`
which began to fail after upgrade to Commerce 2.0.0-beta.5

To fix, I had to change my test to apply the class if the isDefault equals "1":
`class="{% if purchasable.isDefault=='1' %} default {% endif %}"`

### Steps to reproduce

1. In variant for loop, output the following tag to show the value `{{ purchasable.isDefault }}`
2. [Variant Model docs](https://craftcommerce.com/docs/variant-model#isdefault) show it should be `true` or `false`

### Additional info

- Craft version: Craft Solo 3.0.10
- PHP version: 7.0.30
- Database driver & version: MySQL 5.5.60
- Plugins & versions: Craft Commerce 2.0.0-beta.5

**Comment by AugustMiller** [comment]
`1` and `0` are often the string representations of true and false.

If you're using `devMode`, you should try this in your template:

```twig
{{ dump(purchasable.isDefault) }}
```

You're apt to get something like `bool(true)`.

Generally speaking, when comparing booleans, you should use the native types, in Twig:

```twig
{% if purchasable.isDefault == true %}
  It’s the default!
{% endif %}
```

However, it's even simpler, since we know this is a boolean property, and all `if` needs is a truthy value to pass:

```twig
{% if purchasable.isDefault %}
  It’s the default!
{% endif %}
```

When `purchasable.isDefault` is `bool(false)`, the statement won't pass.

Comparing against the string values can be problematic, as you've discovered! What's actually happening is that you're forcing a coercion from `bool(true)` to `string('1')`, and then comparing that to the string `'1'`. This ends up being unnecessary, and potentially error-prone, whereas using the straight booleans don't involve any magic behind-the-scenes.

**Comment by lukeholder** [comment]
Closing, thanks for your explanation August.
