### ISSUE TITLE
Editing address on order detail page in admin bug

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#413]
### Description
When editing/changing an address via the order detail page in the admin, if the shipping and billing addresses are the same but i want to change just the shipping to be different, it changes both not just the single address on save.

### Steps to reproduce

1. go to an order detail page in admin where the shipping and billing addresses are the same
2. change the shipping address so it is different to the billing address
3. save the order

**Comment by AugustMiller** [comment]
This might be “solvable” by adding a `Delete` or `Remove` button to the two addresses.

Addresses are stored discretely from orders, and referenced by an ID. Effectively, you are editing _both_ addresses, rather than copying + modifying, as they're likely both pointed at the same record.

Alternatively, a "Save as new address" could be useful, from the modal…

**Comment by lukeholder** [comment]
When an order is completed, the addresses are copied twice, once for billing and once fo shipping, so a unique ID should be created for each address related to the order.

Sounds like that duplication is not happening, and the original address selected is associated to both billing and shipping.

**Comment by AugustMiller** [comment]
This is a nice strategy—didn't realize that was the case, and had been wondering what happens if a customer updates an address after an order is completed! 👌 

@samuelbirch Is this replicable for Carts only, or is it happening for completed orders, as well? Could you clarify this in the issue description?

**Comment by AugustMiller** [comment]
@lukeholder I understand this might be part of the current design, but I can't see where this is implemented—addresses are not currently duplicated for shipping, nor billing, after the order is completed.

Would you like this filed as a separate bug?

**Comment by AugustMiller** [comment]
@lukeholder Ok, quick update here!

I think this is non-functioning for the same reason that I'd added #433.

Basically, any time an order is saved after it's completed (i.e. when addresses are duplicated and re-assigned), it fails validation, because the addresses no longer belong to the user.

It seems like we need one of two fixes:

1. Within `OrderValidatorTrait::validateAddress`, disable checking against ownership after an order is completed (`if ($order->$address->id && !in_array($address->id, $addressesIds, false)) { ... }`;
2. Opting out of validation when saving orders, in a more methodical/surgical way (i.e. only when we're certain we don't care about the validity, or we're pretty sure it was already validated at the most important time).

Unfortunately, when I make the first change, above, _the addresses are saved along with the `customers_addresses` join record_. It appears as though the `afterSave` Order Element handler re-saves these addresses against the Order's Customer, instead of in its original state.

Thoughts? I'm a little out of my depth, but created augustmiller/commerce@ 8f01520a506a8696a9dc65586c13c61852b5a4cd to record some observations about a method that “worked.”

🙇

**Comment by lukeholder** [comment]
Addresses are not being duplicated on order completion. This also affects: #433

Validation of addresses should not be made regarding a customer if the order is complete.

Will be releasing a fix.
