### ISSUE TITLE
Failed Payment Transaction Marked as Complete

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#419]
### Description

Using a real credit card, we had a checkout transaction that was processed successfully, however, no payment was collected and the Payment status was marked as failed.

https://cl.ly/1M2m2c1Q1H0w

### Steps to reproduce

Unable to reproduce with test cards, the issue came from a live customer card.

### Additional info

I'm not 100% sure on this, but I think the failure might have come after the transaction was redirected to another 3rd party verifier. https://cl.ly/0T0Z3546323j - I'm wondering if the transaction failed, but Commerce acted as if it was successful?

- Craft version: 3.0.11
- PHP version: 7.1
- Database driver & version: Maria 
- Plugins & versions: Commerce 2.0.0-beta6

**Comment by bryantAXS** [comment]
I think I've narrowed down the issue to being that the checkout workflow incorrectly sends a user to the Thank You page and completes the order after a 3D Secure checkout has failed.

I just recreated it on our test enviornment: https://cl.ly/072r1J0P0c1J

**Comment by lukeholder** [comment]
@bryantAXS have you set up the stripe webhook? A processing transaction is the correct transaction to show up when we completed the payment request successfully but are waiting for the webhook to tell us the payment was successful.

**Comment by lukeholder** [comment]
Also guessing the webhook is not hitting your local environment.

**Comment by andris-sevcenko** [comment]
@bryantAXS when using the 3DS flow, there is no way to know the result of the transaction immediately - Commerce has to rely on webhooks instead (https://stripe.com/docs/sources/best-practices#the-required-use-of-webhooks). So, for 3DS flows, there are three transactions happening.

1. Redirect (User gets redirected to 3DS auth site)
2. Processing (User has completed 3DS auth process)
3. Success/Failed (When the webhook is received from Stripe)

When the user is done with 3DS, regardless of the result, the user is returned to the site and the 2nd transaction is created. At that point, Commerce is ready for the webhook that tells it whether the payment was a successful one or not.

So, what you should be doing is checking the order status, because, just because the user got redirected back, it doesn't mean that the payment is a success. The order is marked _complete_ (because all the required user interaction is done), but it will be marked _paid_ when the successful webhook comes in.

**Comment by andris-sevcenko** [comment]
> In that case we're unable to show any "Success" or "Failure" message and instead we write some statement saying "We'll let you know at a later date if the order worked or not"...?

Stripe does not have two different redirect URLs for this (https://stripe.com/docs/sources/three-d-secure#customer-action). 

What you should do is have an order summary page, that checks the `isComplete` property of the Order. This would indicate, that the 3DS flow is complete. A good message to show is "Your payment is being processed". or "Your order is placed." 

> I'm just confused how we're supposed to alert users in a reliable way that their transaction processed successfully, and if not, alert them to this and hope they resubmit payment again? Based on what you're saying, that seems like it's not possible which I have a hard time understanding.

You can even have an ajax request pinging in the background that checks whether `order.getIsPaid()` is true that then modifies the page to show that. In most cases, the first ajax request will fire when the webhook response from Stripe will be received.

You can also go with the odds that most 3DS payments will be completed successfully, assume purchases as successful and then just handle the oddball cases with a plugin that listens for failed transactions and alerts the store manager that there was a problem with a payment.

Another option you have is not using the built-in `getPaymentFormHtml()` method on the gateway and roll your own, one which does not check for 3D Secure at all. This would not protect the store manager, though, in case of disputed payments (https://stripe.com/docs/sources/three-d-secure#disputed-payments)

> The only "flag" we have on our end, is the paid/unpaid state of the order, but as you're saying, that's unreliable because it could be marked as paid after the webhook processes.

That is actually the reliable flag. The `isComplete` flag is trickier.

I mean, I get it - it seems a little frustrating in the beginning, but that's how Stripe works with 3DS. If webhooks aren't used, there's a good chance of getting denied payments for cards that are simply still in the process of being marked as chargeable.

**Comment by andris-sevcenko** [comment]
> Part of this potentially comes from my lack of deep understanding of 3DS so I appreciate the breakdown here.

To be fair, we probably should have more thorough documentation on that on our end as well, even if we're still in Beta.

> One thing that would be helpful though is potentially having the ability to designate another default status. Eg: a default status for a completed order, and a default status for an incomplete order. Doing this would allow us to send out emails alerting the user to when the transaction has been processed by the payment gateway, and we could alert of a success or failure message from there. I think part of the problem currently is we have no way to automate these responses, which unfortunately aren't immediate.

I'm looping @lukeholder back on this, then. What you're saying definitely makes sense and I know we talked about ore advanced Order Status handling, so he's the man to talk to about this.

> I'm actually already rolling my own form, but it sounds like you say it's possible to disable it entirely? How would I do that?

Just looked at the code to refresh my memory. If you never add an input field `threeDSecure` to the payment form, then Commerce/Stripe plugin should attempt to charge it without the 3DS flow. The only exception would be when a card has specified that it requires 3DS, in which case that flow is initiated, anyway, because all charges without 3DS will be denied for such cards.

**Comment by lukeholder** [comment]
@bryantAXS 

I don't think we will be doing automatic status switching based on payment status at the moment. 

Would rather see a generic status change automation builder in core.

Alos, there is already an `order.paidStatus` attribuite with values of either `paid`, `partial`, or `unpaid`. You can use this status in your order confirmation emails and order success screen. The completed status just means the order has been paid or the customer has completed everything they can do to submit the order.

What we probably should do is make it easier to filter the paid status in the order index. I will go ahead and add that to the list. Thanks.
