### ISSUE TITLE
Allow percentage-based Discounts at the Order level

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#438]
It would be *awesome* to be able to offer percentage-based Discounts to order totals.

Most of the existing logic is still valid—but there's apt to be another check, once a Discount matches an order (i.e. if there are no Variants/Products required to match, or a matching one is found in the order), a new `Discount` attribute could get checked (`Discount::baseDiscountPercentage`?), either in addition to `baseDiscount`, or instead of it.

This is probably a bit of a UX issue, as well, but wanted to get the conversation started from an engineering perspective.

Thanks for tuning in!

**Comment by engram-design** [comment]
+1 for this, and just to make sure I'm on the same page. Right now you can set a discount of a dollar value from the total of the cart - this is great, but we'd like this to be a percentage.

Say, we want to have a coupon code that provides 10% off the entire order - a very common scenario I'd imagine. I can set "10% off the discounted item price", but will get a pretty ugly looking cart as below (using coupon code `TEST`).

![screen shot 2019-02-16 at 10 43 37 am](https://user-images.githubusercontent.com/1221575/52890234-c38c6b00-31d7-11e9-8aa6-84c1cd493aeb.png)

The discounts are applied to each line item in the cart, which isn't a great look.

Or - is this possible now in some other fashion?

**Comment by keyurshah** [comment]
Wondering if there’s an update to this?

Thanks

**Comment by nfourtythree** [comment]
Closed by #1131

**Comment by MattWilcox** [comment]
Ok, so how is this done? "Allow Percentage Based Discounts at Order Level..."

Because I tried this:

<img width="1033" alt="Screen Shot 2020-11-11 at 11 11 43" src="https://user-images.githubusercontent.com/814039/98805153-10ce5880-240f-11eb-9438-fa5fb83080db.png">

And got this:

<img width="1033" alt="Screen Shot 2020-11-11 at 11 12 08" src="https://user-images.githubusercontent.com/814039/98805173-162ba300-240f-11eb-92fc-bf81ff310d3f.png">

Which... is not right.

**Comment by gazlawn22** [comment]
What happened with this as I need this facility at the moment, and whats been described above looks exactly right but can't actually see the facility in Craft?
