### ISSUE TITLE
Move EVENT_AFTER_ORDER_PAID back to after order marked as complete and paid

### ISSUE THREAD

**Issue by emilyfitton** [craftcms/commerce#670]
### Description
The change to the setup in here:
https://github.com/craftcms/commerce/commit/80f0f1c93f5db6173fd99a864bb9f4077b2d88b7
Now means that this event is firing before the order is marked as complete and whilst isPaid is still false.

In practice this means that its not possible for a plugin to change the order status of an order after the order is completed.

### Steps to reproduce

1. Trigger event to change order status to a custom status
2. Order status is changed to custom status then back to the default status.

### Additional info

- Craft version:  3.1.2.2
- PHP version: 7.2.2
- Database driver & version: 5.7.19
- Plugins & versions: Commerce Pro 2.0.1

**Comment by lukeholder** [comment]
Hi @emilyfitton not sure I understand, couldn't you use the `Order::EVENT_AFTER_COMPLETE_ORDER` event? Will re-open with response.

**Comment by emilyfitton** [comment]
Yep so I can run Order::EVENT_AFTER_COMPLETE_ORDER and check the order is Paid.

However the docs imply that EVENT_AFTER_ORDER_PAID should run when an order is paid and complete.

> This event is raised after an order is paid and completed
> 
> Plugins can get notified after an order is paid and completed

However in practice what I have found is that when using this event  $order->getIsPaid() is returning false as is $order->isCompleted.

**Comment by andris-sevcenko** [comment]
Hey @emilyfitton 

After digging around the code a bit I think I understand your frustration. In broad strokes you are right. The commit you reference, though, was also wrong, because the event was nested inside the conditionals that also checked if the order was getting completed and some gateway payment flows dictated that sometimes an order would get completed first and paid a bit later, so before that commit was made, the `EVENT_AFTER_ORDER_PAID` was sometimes not fired.

We'll talk about this internally and, if everything seems to be safe with moving that event to after the order is being completed on that request, we'll do so.

**Comment by emilyfitton** [comment]
No problem, its not holding anything up on my end as like you said I can use EVENT_AFTER_COMPLETE_ORDER for now. Just thought it was worth raising what I found along the way.
