### ISSUE TITLE
OrderElement->getNext() always null

### ISSUE THREAD

**Issue by mikegraham00** [craftcms/commerce#754]
### Description

I'm creating a small enhancement plugin for the CP and it appears that OrderElement->getNext() plus getPrev(), next(), and prev() always return null.

### Steps to reproduce
```
Craft::$app->getView()->hook('cp.commerce.order.edit.main-pane', function(array &$context) {
         $order = $context['order'];
         Craft::dd($order->getNext()); //always null even if there are subsequent orders.
}
```
### Additional info

- Craft version: 3.1.13
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by lukeholder** [comment]
The getNext() and getPrev() are only in the context of an element query.
 
Since the order element for the page is not loaded from an element query that only gets the single order, there is no next or previous order in that query.

Both of these methods accept a criteria, so you can pass a query into them and get the next item from those results:

```
Craft::$app->getView()->hook('cp.commerce.order.edit.main-pane', function(array &$context) {
         $order = $context['order'];
         $order->getNext(Order::find());
}
```

This also lets you pass in a query for other orders of the same order status as the current order if you wanted.

Hope that helps.
