### ISSUE TITLE
Missing Documentation on how to migrate commerce elements

### ISSUE THREAD

**Issue by N0ps32** [craftcms/commerce#813]
### Description
IMO there is a lack of documentation on how to write a migration that changes commerce elements like for example, adding a new Product Type.

With project.yaml still being very unstable what is the recommended way to migrate changes from dev to staging to production?

Or if migrations are indeed the way to go can we please get proper documentation for using them in relation with commerce? I can't imagine I'm the only developer that has to maintain multiple development environments.

**Comment by TheFox** [comment]
I also would like to know.

project.yml is too unstable. It's not acceptable for production systems.

**Comment by brandonkelly** [comment]
Project Config is our solution. It’s actually quite stable if you [set it up correctly](https://docs.craftcms.com/v3/project-config.html#enabling-the-project-config-file) and are mindful of the [caveats](https://docs.craftcms.com/v3/project-config.html#caveats).

**Comment by brandonkelly** [comment]
(And like anything else, if you run into bugs, please report them, so we can improve it.)

**Comment by N0ps32** [comment]
Last time I checked (was a while ago so maybe I'm wrong now) commerce didn't even support environment variables in all setting pages making project yaml practically unusable because you couldn't set-up payment gateways and E-Mail settings per env.

Also project.yaml has destroyed more than 3!!! staging environments I've had set up over the course of a few months. Sorry but this feature is still riddled with bugs (there are several open issues that haven't even been solved yet in craft 3 regarding that). Encouraging people to rely on a system like that in an ecommerce production environment is a farce.

You are charging a grand total of 299$ + 999$ for a system that lacks basic documentation in a lot of areas if you're forced to extend the system with PHP. Why do I have to backtrack through pages upon pages of craft source-code for an explanation that should have been provided in the documentation from the get-go?

I know that having a 100% complete documentation is very difficult, especially for a small team, but come on. Why do you even provide that feature if you refuse to document it properly? The response of "use the project yaml" that btw, might nuke your prod env without warning from my experience is frankly a joke.

**Comment by brandonkelly** [comment]
Sorry to hear that project.yaml has caused problems for you. Most likely either your databases weren’t in sync to begin with across your environments, and/or the databases have come out of sync with the project config. The vast majority of project config related issues are a result of one or both of those things.

I’d suggest you start fresh with it, closely following the instructions linked to above, including running the new `project-config/rebuild` command on the primary environment (which yesterday’s Commerce 2.1.3 release added support for). Going forward, be careful to ensure all config changes are being made via services rather than making changes directly in the DB, and ensure no config changes are being made on non-development environments, by disabling the `allowAdminChanges` config setting for them.

Regarding Content Migrations, it was clear from the start with that feature that it wasn't going to be a great solution for making duplicate changes across environments, which is why we shifted efforts to build the Project Config feature instead. Content Migrations are really only well-suited for people building custom applications with Craft, where you need a custom migration track to manage your own custom schema changes., separate from Craft/plugin-related things.

I do agree with you that our documentation needs to be better, both general docs and better PHP examples for the [class reference](https://docs.craftcms.com/commerce/api/v2/), and we are doing our best to improve them, balanced with moving the products forward.
